Repository JuliaGPU/CUDA.jl, pull requests merged in 2020-06, with the labels that each got.

#189 More tests for CUSPARSE
  test/cusparse.jl
Labels: cuda array, tests

#196 Add gemmex wrapper and test
  lib/cublas/wrappers.jl
  test/cublas.jl
Labels: cuda libraries, tests

#197 Fix handling of srcPos and dstPos in unsafe_copy3d!
  lib/cuda/memory.jl
  test/cuda/memory.jl
Labels: bugfix, cuda libraries

#198 Prefer a local CUDA installation when running on CI, reinstate Julia 1.3.
  .gitlab-ci.yml
  Manifest.toml
  Project.toml
  deps/bindeps.jl
  test/runtests.jl
Labels: ci, enhancement

#193 Added wrappers for cusolverDn<t>potrsBatched
  lib/cusolver/wrappers.jl
  test/cusolver.jl
Labels: cuda array, enhancement

#200 Add support for mixed precision
  lib/cutensor/wrappers.jl
  test/cutensor.jl
Labels: cuda libraries, tests

#192 Added wrappers for cusolverDn<t>potrfBatched
  lib/cusolver/wrappers.jl
  test/cusolver.jl
Labels: cuda array, enhancement

#188 Fix cushow tests on Windows.
  test/device/cuda.jl
Labels: cuda kernels, tests

#207 Error throwing tests
  test/cusolver.jl
  test/cusolver/cusparse.jl
Labels: enhancement, tests

#191 fixed gels_batched! issue
  lib/cublas/wrappers.jl
  test/cublas.jl
Labels: bugfix, cuda array

#210 A few more tests for cusparse
  test/cusparse.jl
Labels: cuda libraries, tests

#211 Specialize Base.mightalias for better broadcast performance.
  src/array.jl
  test/array.jl
Labels: cuda array, performance

#221 CUDA 11 compatibility entries
  deps/bindeps.jl
  deps/compatibility.jl
Labels: enhancement

#223 Benchmark suite: tune and cache params
  perf/kernel.jl
  perf/runbenchmarks.jl
Labels: ci, performance

#224 Add benchmarks
  perf/array.jl
  perf/runbenchmarks.jl
Labels: ci, performance

#227 Documentation updates
  docs/Manifest.toml
  docs/Project.toml
  docs/make.jl
  docs/src/tutorials/introduction.jl
  docs/src/usage/array.md
  docs/src/usage/memory.md
  docs/src/usage/workflow.md
Labels: documentation

#230 Don't extend Base.findfirst with an unrelated method.
  src/indexing.jl
Labels: cuda array, enhancement

#233 Memory pinning with interval trees
  Manifest.toml
  Project.toml
  lib/cudadrv/CUDAdrv.jl
  lib/cudadrv/context.jl
  lib/cudadrv/context/primary.jl
  lib/cudadrv/devices.jl
  lib/cudadrv/error.jl
  lib/cudadrv/events.jl
  lib/cudadrv/execution.jl
  lib/cudadrv/libcuda.jl
  lib/cudadrv/libcuda_aliases.jl
  lib/cudadrv/libcuda_common.jl
  lib/cudadrv/memory.jl
  lib/cudadrv/module.jl
  lib/cudadrv/module/function.jl
  lib/cudadrv/module/global.jl
  lib/cudadrv/module/jit.jl
  lib/cudadrv/module/linker.jl
  lib/cudadrv/occupancy.jl
  lib/cudadrv/profile.jl
  lib/cudadrv/stream.jl
  lib/cudadrv/types.jl
  lib/cudadrv/version.jl
  src/CUDA.jl
  test/cudadrv/context.jl
  test/cudadrv/devices.jl
  test/cudadrv/errors.jl
  test/cudadrv/events.jl
  test/cudadrv/execution.jl
  test/cudadrv/memory.jl
  test/cudadrv/module.jl
  test/cudadrv/occupancy.jl
  test/cudadrv/profile.jl
  test/cudadrv/ptx/Makefile
  test/cudadrv/ptx/dummy.cu
  test/cudadrv/ptx/dummy.ptx
  test/cudadrv/ptx/empty.cu
  test/cudadrv/ptx/empty.ptx
  test/cudadrv/ptx/global.cu
  test/cudadrv/ptx/global.ptx
  test/cudadrv/ptx/vadd.cu
  test/cudadrv/ptx/vadd.ptx
  test/cudadrv/ptx/vadd_child.cu
  test/cudadrv/ptx/vadd_child.ptx
  test/cudadrv/ptx/vadd_parent.cu
  test/cudadrv/ptx/vadd_parent.ptx
  test/cudadrv/ptx/vectorops.cu
  test/cudadrv/ptx/vectorops.ptx
  test/cudadrv/stream.jl
  test/cudadrv/version.jl
Labels: cuda libraries, enhancement

#244 Retry cudnnCreate on CUDNN_STATUS_INTERNAL_ERROR and CUDNN_STATUS_NOT_INITIALIZED
  lib/cublas/error.jl
  lib/cudnn/base.jl
  lib/cudnn/error.jl
  lib/cufft/error.jl
  lib/curand/error.jl
  lib/cusolver/error.jl
  lib/cusparse/error.jl
  lib/cutensor/error.jl
  src/memory.jl
  test/memory.jl
Labels: bugfix, cuda array

#245 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  deps/bindeps.jl
  lib/cublas/wrappers.jl
  lib/cupti/CUPTI.jl
  lib/cupti/wrappers.jl
  lib/curand/wrappers.jl
  lib/cusparse/wrappers.jl
  src/utilities.jl
  test/cublas.jl
  test/cudnn.jl
  test/cufft.jl
  test/curand.jl
  test/cusparse.jl
  test/cutensor.jl
  test/utils.jl
Labels: enhancement

#241 Replace slash by path separator to properly skip tests on Windows.
  test/runtests.jl
Labels: bugfix, tests

#234 Better nsys detection.
  lib/cudadrv/profile.jl
Labels: bugfix, installation

#248 Import wrapper tooling, wrap NVML
  lib/cudadrv/devices.jl
  lib/cudadrv/libcuda.jl
  lib/cudadrv/libcuda_common.jl
  lib/cudadrv/version.jl
  lib/cupti/CUPTI.jl
  lib/cupti/libcupti.jl
  lib/cupti/libcupti_common.jl
  lib/nvml/NVML.jl
  lib/nvml/device.jl
  lib/nvml/error.jl
  lib/nvml/libnvml.jl
  lib/nvml/libnvml_common.jl
  lib/nvml/system.jl
  res/wrap/.gitignore
  res/wrap/Manifest.toml
  res/wrap/Project.toml
  res/wrap/README.md
  res/wrap/patches/cudadrv/batched_memop.patch
  res/wrap/patches/cudadrv/cudeviceptr.patch
  res/wrap/patches/cudnn/algorithm.patch
  res/wrap/patches/cudnn/severity.patch
  res/wrap/patches/cusolver/dup.patch
  res/wrap/patches/cusparse/deprecated.patch
  res/wrap/patches/cusparse/matdescr.patch
  res/wrap/patches/nvtx/macro.patch
  res/wrap/patches/nvtx/unions.patch
  res/wrap/pointers.json
  res/wrap/wrap.jl
  src/CUDA.jl
  src/utilities.jl
  test/cudadrv/context.jl
  test/cudadrv/devices.jl
  test/cudadrv/errors.jl
  test/cudadrv/events.jl
  test/cudadrv/execution.jl
  test/cudadrv/memory.jl
  test/cudadrv/module.jl
  test/cudadrv/occupancy.jl
  test/cudadrv/stream.jl
  test/cudadrv/version.jl
  test/device/array.jl
  test/device/cuda.jl
  test/device/pointer.jl
  test/nvml.jl
  test/runtests.jl
  test/setup.jl
Labels: cuda libraries

#251 Ignore some potentially unsupported NVML features.
  test/nvml.jl
Labels: cuda libraries, tests

#209 Add texture support from CuTextures.jl
  docs/src/api/kernel.md
  docs/src/lib/driver.md
  lib/cudadrv/CUDAdrv.jl
  lib/cudadrv/libcuda_common.jl
  lib/cudadrv/memory.jl
  src/CUDA.jl
  src/device/texture.jl
  src/pointer.jl
  src/texture.jl
  test/texture.jl
Labels: cuda kernels, enhancement
