Repository JuliaGPU/CUDA.jl, pull requests merged in 2020-07, with the labels that each got.

#268 Retry library initialization failure due to (badly reported) OOM.
  lib/cublas/CUBLAS.jl
  lib/cublas/wrappers.jl
  lib/cudnn/base.jl
  lib/curand/random.jl
  lib/curand/wrappers.jl
  lib/cusolver/wrappers.jl
  lib/cusparse/wrappers.jl
Labels: cuda libraries, enhancement

#269 Upgrade CUTENSOR to v1.1.0.
  Artifacts.toml
  deps/bindeps.jl
Labels: cuda libraries

#274 Improve local CUDA discovery for CUDA 11
  deps/bindeps.jl
  deps/discovery.jl
Labels: bugfix, installation

#280 Add and document a non-blocking version of at-sync.
  docs/src/development/profiling.md
  src/utilities.jl
  test/utils.jl
Labels: performance

#281 Use a custom adaptor for cu so that adapt(CuArray) preserves element types.
  src/array.jl
  test/array.jl
  test/cublas.jl
  test/cudnn.jl
  test/nnlib.jl
Labels: cuda array

#284 Check and warn for library versions.
  src/initialization.jl
Labels: cuda libraries

#243 Host-side CUTENSOR
  .gitlab-ci.yml
  lib/cudadrv/memory.jl
  lib/cutensor/libcutensor.jl
  lib/cutensor/wrappers.jl
  res/wrap/pointers.json
  test/cudadrv/memory.jl
  test/cutensor.jl
Labels: bug, cuda libraries, enhancement, tests

#288 Add note about nvml dll missing
  docs/src/installation/troubleshooting.md
Labels: documentation

#291 Support CUDA 11
  .gitlab-ci.yml
  Artifacts.toml
  deps/bindeps.jl
  lib/cublas/libcublas.jl
  lib/cublas/libcublas_common.jl
  lib/cublas/wrappers.jl
  lib/cudadrv/CUDAdrv.jl
  lib/cudadrv/context.jl
  lib/cudadrv/context/primary.jl
  lib/cudadrv/devices.jl
  lib/cudadrv/events.jl
  lib/cudadrv/libcuda.jl
  lib/cudadrv/libcuda_aliases.jl
  lib/cudadrv/libcuda_common.jl
  lib/cudadrv/libcuda_old.jl
  lib/cudadrv/memory.jl
  lib/cudadrv/module/global.jl
  lib/cudadrv/module/linker.jl
  lib/cudadrv/stream.jl
  lib/cufft/libcufft_common.jl
  lib/cupti/libcupti.jl
  lib/cupti/libcupti_common.jl
  lib/curand/libcurand_common.jl
  lib/cusolver/libcusolver.jl
  lib/cusolver/libcusolver_common.jl
  lib/cusolver/wrappers.jl
  lib/cusparse/CUSPARSE.jl
  lib/cusparse/array.jl
  lib/cusparse/interfaces.jl
  lib/cusparse/libcusparse.jl
  lib/cusparse/libcusparse_common.jl
  lib/cusparse/libcusparse_old.jl
  lib/cusparse/wrappers.jl
  lib/cutensor/libcutensor_common.jl
  lib/nvml/libnvml.jl
  lib/nvml/libnvml_common.jl
  res/wrap/Manifest.toml
  res/wrap/Project.toml
  res/wrap/patches/cublas/computetype.patch
  res/wrap/patches/cudadrv/cuarray.patch
  res/wrap/patches/cusolver/dup.patch
  res/wrap/patches/cusparse/cppversion.patch
  res/wrap/patches/cusparse/deprecated.patch
  res/wrap/patches/cusparse/matdescr.patch
  res/wrap/pointers.json
  test/cublas.jl
  test/cusolver/cusparse.jl
  test/cusparse.jl
Labels: ci, cuda libraries

#295 Don't use a typevar for the array parent.
  src/array.jl
Labels: cuda array

#299 Optimizations for broadcast
  Manifest.toml
  lib/cudadrv/execution.jl
  lib/cudadrv/occupancy.jl
  src/compiler/execution.jl
  src/gpuarrays.jl
Labels: cuda kernels, performance

#25 Re-enable threading tests.
  src/pool.jl
  src/pool/binned.jl
  src/pool/dummy.jl
  src/pool/simple.jl
  src/pool/split.jl
  test/threading.jl
Labels: bugfix, ci, cuda array

#310 Artifact improvements for CUDA 11 on Windows
  deps/bindeps.jl
  deps/discovery.jl
  test/setup.jl
Labels: installation

#313 Optimize element-wise operations
  Manifest.toml
  lib/cudadrv/execution.jl
  src/device/intrinsics/memory_shared.jl
  src/gpuarrays.jl
Labels: cuda array, performance

#309 Test runner improvements for multigpu mode
  test/runtests.jl
Labels: ci, enhancement

#314 Check if reported GPU memory use is available.
  lib/nvml/device.jl
  test/runtests.jl
  test/setup.jl
Labels: bugfix

#315 Update artifacts: include cusolverMg, and use Yggdrasil binaries.
  Artifacts.toml
Labels: cuda libraries, dependencies

#317 Fix invalid conversion of pointer to signed integer.
  lib/utils/call.jl
Labels: bugfix

#316 Specialization fixes for mapreducedim.
  Manifest.toml
  src/mapreduce.jl
Labels: cuda array, performance

#319 Work around (presumed) Windows driver bug in exception test.
  src/compiler/exceptions.jl
  test/execution.jl
Labels: tests

#325 Bump CUDNN and CUTENSOR
  .gitlab-ci.yml
  Artifacts.toml
  deps/bindeps.jl
  deps/discovery.jl
  src/initialization.jl
Labels: installation

#328 Simplify discovering binaries by using Sys.which.
  deps/discovery.jl
Labels: installation

#331 Attach CUSPARSE docstrings to bare methods, not empty functions.
  lib/cusolver/wrappers.jl
  lib/cusparse/wrappers.jl
Labels: bugfix, cuda array

#332 Eagerly reduce the amount of worker threads.
  test/runtests.jl
  test/setup.jl
Labels: ci

#329 Add wrapper for NVML utilization rates.
  lib/nvml/device.jl
  test/nvml.jl
Labels: cuda libraries

#334 Clean-up library wrappers [NFC]
  lib/cublas/util.jl
  lib/cublas/wrappers.jl
  lib/cusolver/util.jl
  lib/cusolver/wrappers.jl
  lib/cusparse/CUSPARSE.jl
  lib/cusparse/helpers.jl
  lib/cusparse/types.jl
  lib/cusparse/util.jl
  lib/cusparse/wrappers.jl
  lib/cutensor/wrappers.jl
  lib/library_types.jl
  test/cublas.jl
  test/cusolver.jl
  test/cusparse.jl
Labels: cuda libraries

#337 Fix type stability of Statistics.var with dims.
  src/statistics.jl
  test/statistics.jl
Labels: performance

#335 Fix CUDNN v8 discovery and loading on Windows
  deps/bindeps.jl
  deps/discovery.jl
Labels: installation

#338 Fix parameter alignment for dynamic parallelism.
  src/device/intrinsics/dynamic_parallelism.jl
  test/execution.jl
Labels: bugfix, cuda kernels
