Repository JuliaGPU/CUDA.jl, pull requests merged in 2020-09, with the labels that each got.

#404 Fix bounds checking with GPU views.
  src/subarray.jl
  test/array.jl
Labels: bugfix, cuda array

#408 Fix some wrong pointer types in the CUDNN headers.
  lib/cudnn/libcudnn.jl
  res/wrap/pointers.json
Labels: bugfix, cuda libraries

#407 Force specialization for dynamic_cudacall to support more arguments.
  src/compiler/execution.jl
  test/execution.jl
Labels: bugfix

#409 Refactor CUSPARSE
  lib/cusparse/CUSPARSE.jl
  lib/cusparse/array.jl
  lib/cusparse/conversions.jl
  lib/cusparse/generic.jl
  lib/cusparse/interfaces.jl
  lib/cusparse/level1.jl
  lib/cusparse/level2.jl
  lib/cusparse/level3.jl
  lib/cusparse/libcusparse_old.jl
  lib/cusparse/preconditioners.jl
  test/cusparse.jl
Labels: bugfix, cuda array, enhancement

#414 Simplify library wrappers by introducing a CUDA Ref
  lib/cublas/CUBLAS.jl
  lib/cublas/libcublas.jl
  lib/cublas/linalg.jl
  lib/cublas/wrappers.jl
  lib/cudnn/CUDNN.jl
  lib/cudnn/activation.jl
  lib/cudnn/batchnorm.jl
  lib/cudnn/conv.jl
  lib/cudnn/libcudnn.jl
  lib/cudnn/pooling.jl
  lib/cudnn/tensor.jl
  lib/curand/CURAND.jl
  lib/cusolver/CUSOLVER.jl
  lib/cusparse/CUSPARSE.jl
  lib/cusparse/level1.jl
  lib/cusparse/level2.jl
  lib/cusparse/level3.jl
  lib/cusparse/libcusparse.jl
  lib/cusparse/libcusparse_old.jl
  lib/cutensor/CUTENSOR.jl
  lib/cutensor/wrappers.jl
  src/pointer.jl
  test/cublas.jl
  test/cutensor.jl
  test/cutensor/base.jl
  test/cutensor/contractions.jl
  test/cutensor/elementwise_binary.jl
  test/cutensor/elementwise_trinary.jl
  test/cutensor/permutations.jl
  test/cutensor/reductions.jl
  test/pointer.jl
  test/runtests.jl
Labels: cuda libraries

#416 Simplify and update wrappers
  lib/cublas/libcublas.jl
  lib/cublas/libcublas_common.jl
  lib/cudadrv/CUDAdrv.jl
  lib/cudadrv/libcuda.jl
  lib/cudadrv/libcuda_common.jl
  lib/cudadrv/libcuda_deprecated.jl
  lib/cudnn/CUDNN.jl
  lib/cudnn/libcudnn.jl
  lib/cudnn/libcudnn_common.jl
  lib/cudnn/libcudnn_deprecated.jl
  lib/cufft/libcufft.jl
  lib/cufft/libcufft_common.jl
  lib/cupti/libcupti.jl
  lib/cupti/libcupti_common.jl
  lib/curand/libcurand.jl
  lib/curand/libcurand_common.jl
  lib/cusolver/libcusolver.jl
  lib/cusolver/libcusolver_common.jl
  lib/cusparse/CUSPARSE.jl
  lib/cusparse/libcusparse.jl
  lib/cusparse/libcusparse_common.jl
  lib/cusparse/libcusparse_deprecated.jl
  lib/cutensor/libcutensor.jl
  lib/cutensor/libcutensor_common.jl
  lib/nvml/libnvml.jl
  lib/nvml/libnvml_common.jl
  lib/nvtx/libnvtx.jl
  lib/nvtx/libnvtx_common.jl
  res/wrap/Manifest.toml
  res/wrap/Project.toml
  res/wrap/README.md
  res/wrap/patches/cublas/computetype.patch
  res/wrap/patches/cudadrv/batched_memop.patch
  res/wrap/pointers.json
  res/wrap/wrap.jl
Labels: cuda libraries

#417 GEMM improvements
  Manifest.toml
  Project.toml
  README.md
  lib/cublas/CUBLAS.jl
  lib/cublas/libcublas.jl
  lib/cublas/linalg.jl
  lib/cublas/wrappers.jl
  lib/library_types.jl
  src/CUDA.jl
  src/array.jl
  src/state.jl
  test/cublas.jl
Labels: cuda array

#425 Improve init error message
  deps/bindeps.jl
  src/initialization.jl
Labels: enhancement, installation

#428 CUFFT-related optimizations
  lib/cufft/fft.jl
  src/array.jl
Labels: cuda libraries, performance

#429 Fix reverse/view regression
  src/array.jl
Labels: cuda array, performance

#421 add CuSparseMatrixCOO
  lib/cusparse/array.jl
  lib/cusparse/conversions.jl
  test/cusparse.jl
Labels: cuda array, enhancement

#424 Global math mode for easy use of lower-precision functionality
  lib/cublas/CUBLAS.jl
  lib/cublas/libcublas.jl
  lib/cublas/wrappers.jl
  src/state.jl
Labels: cuda libraries, performance

#433 Update packages
  Manifest.toml
  Project.toml
Labels: dependencies

#321 Performance improvements by calling cuDNN API
  Manifest.toml
  lib/cudnn/CUDNN.jl
  lib/cudnn/activation.jl
  lib/cudnn/batchnorm.jl
  lib/cudnn/conv.jl
  lib/cudnn/nnlib.jl
  lib/cudnn/pooling.jl
  lib/cudnn/softmax.jl
  lib/cudnn/tensor.jl
Labels: cuda libraries, performance

#436 Retry curandGenerateSeeds when OOM.
  lib/curand/random.jl
Labels: cuda libraries

#435 Introduce StridedCuArray
  lib/cublas/linalg.jl
  lib/cublas/wrappers.jl
  src/array.jl
  src/subarray.jl
  test/cublas.jl
Labels: cuda array

#439 Fix and test reverse on wrapped array.
  Project.toml
  src/array.jl
  src/pointer.jl
  test/array.jl
Labels: bugfix, cuda array

#441 Fixes after recent array wrapper changes
  Manifest.toml
  lib/curand/random.jl
  src/accumulate.jl
  src/array.jl
  src/indexing.jl
  src/mapreduce.jl
  src/random.jl
  src/reverse.jl
Labels: cuda array

#444 Fix finalization of copied arrays.
  src/array.jl
Labels: bugfix, cuda array

#443 Provide CUBLAS with a pool-backed workspace.
  lib/cublas/CUBLAS.jl
Labels: cuda libraries

#442 Adapt to GPUArrays changes.
  Manifest.toml
  src/broadcast.jl
  src/gpuarrays.jl
Labels: dependencies

#438 Array simplifications
  lib/cusolver/linalg.jl
  src/array.jl
  test/array.jl
  test/cusolver.jl
Labels: cuda array

#445 Support for/Add CUDA 11.1
  .gitlab-ci.yml
  Artifacts.toml
  deps/bindeps.jl
  deps/compatibility.jl
  deps/discovery.jl
Labels: installation

#450 Allow use of strided vectors with mul! (gemv! and gemm!)
  lib/cublas/linalg.jl
  lib/cublas/wrappers.jl
  src/pointer.jl
  test/cublas.jl
Labels: cuda array

#451 Have convert call CuSparseArray's constructors.
  lib/cusparse/array.jl
Labels: cuda array
