Repository JuliaGPU/CUDA.jl, pull requests merged in 2020-12, with the labels that each got.

#583 Implement Statistics.varm/stdm instead of Statistics._var
  src/statistics.jl
Labels: cuda array, enhancement

#584 Test for #558.
  test/device/intrinsics.jl
Labels: cuda kernels, tests

#585 Add a quick failure option to the test runner.
  .buildkite/pipeline.yml
  test/runtests.jl
Labels: ci, tests

#596 Update dependencies.
  Manifest.toml
Labels: dependencies

#593 Catch all initialization errors.
  src/initialization.jl
Labels: installation
