Repository JuliaGPU/CUDA.jl, pull requests merged in 2020-10, with the labels that each got.

#460 Cubic texture interpolation
  Project.toml
  src/device/texture.jl
  src/texture.jl
  test/texture.jl
Labels: cuda array, enhancement

#464 Remove duplicate comment
  docs/src/tutorials/introduction.jl
Labels: documentation

#471 Fix initialization of global state
  docs/src/usage/multigpu.md
  src/initialization.jl
  src/state.jl
Labels: bugfix

#472 Remove 'view' implementation.
  src/device/array.jl
Labels: bugfix, cuda kernels

#476 typo: libcuda.dll -> libcuda.so on Linux
  docs/src/installation/overview.md
Labels: documentation

#489 Convert AbstractArray{ComplexF64} to CuArray{ComplexF32} by default
  src/array.jl
  test/array.jl
Labels: cuda array

#486 Fix versioned dylib discovery.
  deps/discovery.jl
Labels: installation

#495 Use dense array types in sparse wrappers.
  lib/cusparse/generic.jl
  lib/cusparse/interfaces.jl
  test/cusparse.jl
Labels: bugfix

#498 Revert array wrapper union changes
  Manifest.toml
  src/array.jl
  src/pool.jl
  test/array.jl
Labels: cuda array

#506 Upgrade artifacts for CUDA 11 compatibility.
  .gitlab-ci.yml
  Artifacts.toml
  deps/bindeps.jl
  lib/cutensor/wrappers.jl
Labels: installation

#507 Update dependencies.
  Manifest.toml
  Project.toml
Labels: dependencies

#508 Convert unsigned short ints to Cint for printf.
  src/device/intrinsics/output.jl
Labels: bugfix, cuda kernels

#503 Dynamically choose versioned libcuda
  src/initialization.jl
Labels: bugfix

#502 Use versioned libcuda
  src/initialization.jl
Labels: installation

#512 Fix reshape with missing dimensions.
  src/array.jl
  test/array.jl
Labels: bugfix, cuda array

#500 mapreduce: change iteration for compatibility with non-commutative operators.
  src/mapreduce.jl
Labels: cuda array

#454 Use the correct CUDNN scaling parameter type.
  lib/cudnn/activation.jl
  lib/cudnn/batchnorm.jl
  lib/cudnn/conv.jl
  lib/cudnn/pooling.jl
  lib/cudnn/softmax.jl
  lib/cudnn/tensor.jl
  lib/cudnn/util.jl
Labels: bugfix, cuda libraries

#515 Fix CUDNN-optimized activation broadcasts
  lib/cudnn/activation.jl
  lib/cudnn/nnlib.jl
  lib/cudnn/tensor.jl
  test/cudnn.jl
Labels: bugfix, cuda array

#517 Fix cooperative launch test.
  test/execution.jl
Labels: tests

#519 CUTENSOR fixes on Windows
  lib/cutensor/interfaces.jl
  lib/cutensor/tensor.jl
  lib/cutensor/wrappers.jl
  test/cutensor/contractions.jl
  test/cutensor/elementwise_binary.jl
  test/cutensor/elementwise_trinary.jl
  test/cutensor/permutations.jl
  test/cutensor/reductions.jl
Labels: bugfix, cuda libraries
