Repository JuliaGPU/CUDA.jl, pull requests merged in 2020-11, with the labels that each got.

#531 Fix and test svd!
  lib/cusolver/linalg.jl
  test/cusolver.jl
Labels: bugfix, cuda array, cuda libraries

#537 Fully move to Buildkite.
  .buildkite/pipeline.yml
  .gitlab-ci.yml
  bors.toml
Labels: ci

#540 Add unit_diag option for sv2! functions
  lib/cusparse/interfaces.jl
  lib/cusparse/level2.jl
  test/cusparse.jl
Labels: cuda array, enhancement

#534 Use type symbols to generate wrapper methods
  lib/cusolver/wrappers.jl
Labels: bugfix, cuda libraries

#543 Documentation fixes
  docs/make.jl
  docs/src/usage/array.md
Labels: documentation

#545 Fix broken checkbounds for CuSparseMatrixCSR and tests
  lib/cusparse/array.jl
  test/cusparse.jl
Labels: bugfix, cuda array

#551 Don't use explicit per-stream threads.
  lib/cudadrv/stream.jl
  src/array.jl
Labels: cuda libraries

#539 Allow `PermutedDimsArray` in `gemm_strided_batched`
  Manifest.toml
  Project.toml
  lib/cublas/wrappers.jl
  src/array.jl
  src/nnlib.jl
  test/nnlib.jl
Labels: cuda array, enhancement

#554 Use structs for texture intrinsic return types.
  src/device/texture.jl
Labels: bugfix, cuda kernels

#562 Correct dims error
  src/array.jl
Labels: bugfix

#535 Support all combinations of datatypes and transposes/adjoints in LinearAlgebra
  lib/cusparse/generic.jl
  lib/cusparse/interfaces.jl
  lib/cusparse/level3.jl
  test/cusparse.jl
  test/cusparse/interfaces.jl
Labels: cuda array, enhancement

#569 Support for 'delayed kernels'
  examples/pairwise.jl
  examples/peakflops.jl
  perf/kernel.jl
  src/accumulate.jl
  src/compiler/execution.jl
  src/gpuarrays.jl
  src/indexing.jl
  src/mapreduce.jl
  test/execution.jl
  test/texture.jl
Labels: cuda kernels, enhancement

#571 Run cuda-memcheck as part of CI
  .buildkite/pipeline.yml
  test/codegen.jl
  test/cublas.jl
  test/cudadrv/module.jl
  test/execution.jl
  test/initialization.jl
  test/pool.jl
  test/runtests.jl
  test/setup.jl
Labels: ci

#573 Update artifacts to include cuda-memcheck
  Artifacts.toml
  deps/bindeps.jl
  test/runtests.jl
Labels: tests

#572 Use at-sync instead of calls to synchronize in tests.
  test/cublas.jl
  test/cutensor/contractions.jl
  test/cutensor/elementwise_binary.jl
  test/cutensor/elementwise_trinary.jl
  test/cutensor/permutations.jl
  test/cutensor/reductions.jl
  test/device/intrinsics.jl
  test/device/ldg.jl
  test/exceptions.jl
  test/execution.jl
  test/setup.jl
Labels: tests

#576 New findmin/max implementation using single-pass reduction
  src/indexing.jl
  test/array.jl
Labels: bugfix, cuda array, performance

#577 Fix synchronization before testing cublasXt calls.
  lib/cublas/CUBLAS.jl
  lib/cublas/wrappers.jl
  test/cublas.jl
Labels: cuda libraries, tests

#575 Improve LinearAlgebra impl methods for triangular types
  lib/cublas/linalg.jl
  lib/cusparse/interfaces.jl
  lib/cusparse/level2.jl
  lib/cusparse/level3.jl
  test/cublas.jl
  test/cusparse.jl
Labels: cuda array

#582 Fix used memory reporting.
  src/pool.jl
Labels: bugfix, cuda array
