Repository JuliaGPU/CUDA.jl, pull requests merged in 2020-05, with the labels that each got.

#21 Don't use BinaryBuilder for most CI tests.
  .gitlab-ci.yml
Labels: ci

#20 Improve initialization for threading
  src/initialization.jl
  test/array.jl
  test/execution.jl
  test/setup.jl
  test/threading.jl
Labels: bugfix

#19 Initialize the memory pool
  Project.toml
  codecov.yml
  src/initialization.jl
  src/memory.jl
Labels: bugfix, cuda array

#22 Remove use of spinlock
  src/memory.jl
  src/memory/binned.jl
  src/memory/dummy.jl
  src/memory/simple.jl
  src/memory/split.jl
Labels: enhancement

#23 Add documentation from CUDAnative/CUDAdrv
  docs/Manifest.toml
  docs/make.jl
  docs/src/api/array.md
  docs/src/api/compiler.md
  docs/src/api/essentials.md
  docs/src/api/kernel.md
  docs/src/installation/conditional.md
  docs/src/lib/driver.md
  lib/cuda/context/primary.jl
  lib/cuda/module/linker.jl
  lib/cuda/types.jl
  src/compiler/execution.jl
  src/device/cuda/output.jl
  src/device/cuda/wmma.jl
  src/initialization.jl
  test/device/wmma.jl
Labels: documentation

#24 Let runners decide which image to use.
  .gitlab-ci.yml
Labels: ci

#18 Don't DCE the exception flag.
  src/compiler/exceptions.jl
Labels: codegen, enhancement

#180 Fix sparse-dense matmul, with transposed dense
  lib/cusparse/interfaces.jl
  test/cusparse.jl
Labels: bugfix, cuda array

#184 Behave like Base wrt. test flags.
  test/runtests.jl
Labels: bugfix, ci

#179 include potri and test
  lib/cusolver/wrappers.jl
  test/cusolver.jl
Labels: cuda array, enhancement

#185 fix sparse CSC gemm and test (closes #181)
  lib/cusparse/wrappers.jl
  test/cusparse.jl
Labels: bugfix, cuda array

#187 Add inplace test for rand
  test/curand.jl
Labels: cuda array, tests
