Repository JuliaGPU/CUDA.jl, pull requests merged in 2021-06, with the labels that each got.

#948 Select devices without NVML.
  test/runtests.jl
Labels: ci

#941 Support isbits union element types with CuArray.
  src/array.jl
  src/device/array.jl
  test/array.jl
  test/device/array.jl
Labels: cuda array, enhancement

#959 Enable sorting with reduced block sizes
  src/sorting.jl
  test/sorting.jl
Labels: bugfix, cuda array

#891 Enable location and debug info.
  .buildkite/pipeline.yml
  src/compiler/execution.jl
  src/compiler/gpucompiler.jl
  test/exceptions.jl
  test/setup.jl
Labels: cuda kernels, upstream

#972 Fix disambiguation of CUDA 11.1 using CUSOLVER.
  deps/bindeps.jl
  deps/compatibility.jl
Labels: installation

#986 Rework memoization
  Manifest.toml
  Project.toml
  deps/Deps.jl
  deps/bindeps.jl
  deps/compatibility.jl
  lib/cublas/CUBLAS.jl
  lib/cublas/wrappers.jl
  lib/cudadrv/CUDAdrv.jl
  lib/cudadrv/devices.jl
  lib/cudadrv/memory.jl
  lib/cudadrv/version.jl
  lib/cudnn/CUDNN.jl
  lib/cudnn/base.jl
  lib/cufft/CUFFT.jl
  lib/cufft/wrappers.jl
  lib/cupti/CUPTI.jl
  lib/cupti/wrappers.jl
  lib/curand/CURAND.jl
  lib/curand/wrappers.jl
  lib/cusolver/CUSOLVER.jl
  lib/cusolver/base.jl
  lib/cusparse/CUSPARSE.jl
  lib/cusparse/management.jl
  lib/cutensor/CUTENSOR.jl
  lib/cutensor/wrappers.jl
  lib/nvml/NVML.jl
  lib/nvml/system.jl
  lib/nvtx/NVTX.jl
  lib/utils/APIUtils.jl
  lib/utils/memoization.jl
  src/CUDA.jl
  src/compiler/gpucompiler.jl
  src/pool.jl
Labels: performance

#990 Perform type conversions in at-atomic.
  src/device/intrinsics/atomics.jl
  test/device/intrinsics/atomics.jl
Labels: cuda kernels, enhancement

#997 Optimize PerDevice for abstract element types.
  src/state.jl
Labels: performance

#996 Optimize library handles
  lib/cublas/CUBLAS.jl
  lib/cudnn/CUDNN.jl
  lib/curand/CURAND.jl
  lib/cusolver/CUSOLVER.jl
  lib/cusparse/CUSPARSE.jl
  lib/cutensor/CUTENSOR.jl
Labels: cuda libraries, performance

#1006 Fixes for artifact loading.
  deps/bindeps.jl
Labels: installation

#1010 More fixes to artifact discovery.
  deps/bindeps.jl
Labels: installation

#1009 Use a plain integer to keep track of pool last use time.
  src/pool.jl
Labels: bugfix

#1016 Move refcounting to an array storage type
  src/array.jl
  src/pool.jl
  test/array.jl
  test/iterator.jl
  test/pointer.jl
  test/pool.jl
Labels: performance
