Repository JuliaGPU/CUDA.jl, pull requests merged in 2021-08, with the labels that each got.

#1073 lib: cusparse: fix #962
  lib/cusparse/interfaces.jl
  test/cusparse/interfaces.jl
Labels: bugfix, cuda array

#1082 Extend and switch to the new CUDA RNG
  Manifest.toml
  Project.toml
  lib/curand/CURAND.jl
  lib/curand/random.jl
  src/random.jl
  test/random.jl
Labels: enhancement, cuda array

#1084 Support/bump for CUDA 11.4.1 and CUDNN 8.2.2
  Artifacts.toml
  deps/bindeps.jl
  deps/discovery.jl
Labels: installation

#1086 Use sincos from libdevice to perform illegal global load.
  src/device/intrinsics/math.jl
  test/device/intrinsics/math.jl
Labels: bugfix, cuda kernels

#1096 lib cusparse: fix #1095 (broken sparse matrix-matrix multiplication with transpose operation)
  lib/cusparse/interfaces.jl
  test/cusparse/interfaces.jl
Labels: bugfix, cuda libraries

#1098 Support more inplace atomic operations.
  src/device/intrinsics/atomics.jl
  test/device/intrinsics/atomics.jl
Labels: enhancement, cuda kernels

#1099 Backports for 3.3.6
  Project.toml
  lib/cusparse/interfaces.jl
  test/cusparse/interfaces.jl
Labels: backport

#1100 Update GPUArrays and GPUCompiler.
  Manifest.toml
Labels: dependencies

#1103 Release hotfixes
  lib/cudadrv/memory.jl
  lib/cudnn/convolution.jl
  src/array.jl
  src/initialization.jl
  src/pool.jl
Labels: bugfix

#1104 Reverse CI for NNlibCUDA.jl
  .buildkite/pipeline.yml
Labels: ci

#1109 Specialize Ref{<:Type} for GPU compatibility.
  src/compiler/execution.jl
  test/broadcast.jl
Labels: enhancement, cuda array

#217 add symmetric support for mul
  lib/cublas/linalg.jl
  test/cublas.jl
Labels: enhancement, cuda array
