Repository JuliaGPU/CUDA.jl, pull requests merged in 2021-12, with the labels that each got.

#1257 Use Base functionality for iteration Union type components.
  src/device/array.jl
  test/array.jl
Labels: cuda array, bugfix

#1260 Bump CI to Julia 1.7.
  .buildkite/pipeline.yml
Labels: ci

#1265 Use CUDA APIs for unoptimized copies.
  src/array.jl
Labels: enhancement, cuda array

#1267 Bump CUDNN to 8.3.1, enable CUDA 11.5 by default.
  Artifacts.toml
  deps/bindeps.jl
Labels: installation

#1272 Fix sort! return type.
  src/sorting.jl
  test/sorting.jl
Labels: cuda array, bugfix

#1269 Adding stream update for inplace complex FFT
  lib/cufft/fft.jl
  test/cufft.jl
Labels: bugfix, cuda libraries

#1277 Allow copies between unified arrays in different contexts.
  src/array.jl
  test/array.jl
Labels: cuda array, bugfix

#1279 Make CUDNN depend on CUBLAS.
  deps/bindeps.jl
Labels: installation

#1288 Improvements for isbits union shared memory
  src/device/array.jl
  src/device/intrinsics/memory_shared.jl
  test/device/intrinsics/memory.jl
Labels: bugfix, cuda kernels

#1293 Bump CUDNN artifacts
  Artifacts.toml
Labels: installation

#1295 Correctly handle missing cached_memory.
  lib/cudnn/convolution.jl
Labels: bugfix, cuda libraries
