Repository JuliaGPU/CUDA.jl, pull requests merged in 2021-07, with the labels that each got.

#1032 just some simple printing tests
  test/cudadrv/devices.jl
  test/cudadrv/stream.jl
Labels: tests

#1034 Test for is_capturing
  test/cudadrv/graph.jl
Labels: tests

#1035 Tests for buffer printing
  test/cudadrv/memory.jl
Labels: tests

#1038 Allow strided inputs to various library functions.
  lib/cublas/wrappers.jl
  lib/cusolver/dense.jl
  lib/cusparse/level3.jl
Labels: cuda libraries

#1056 Add test for math_mode
  test/initialization.jl
Labels: tests

#1059 Streamline atomics.
  Manifest.toml
  Project.toml
  src/device/intrinsics/atomics.jl
  test/device/intrinsics/atomics.jl
Labels: cuda kernels, enhancement

#1033 Detect common integer exponentiations and handle them directly.
  src/device/intrinsics/math.jl
Labels: performance

#1060 Add support for device capability-dependent code.
  Manifest.toml
  src/device/intrinsics.jl
  src/device/intrinsics/atomics.jl
  src/device/intrinsics/version.jl
Labels: cuda kernels

#1063 Add special constructors to work around Base AbstractQ size weirdness.
  Manifest.toml
  src/array.jl
  src/linalg.jl
  test/array.jl
  test/linalg.jl
Labels: bugfix, cuda array

#1023 Add support for unified arrays.
  Manifest.toml
  lib/cusparse/array.jl
  src/array.jl
  src/broadcast.jl
  src/pool.jl
  test/array.jl
Labels: cuda array, enhancement
