Repository JuliaGPU/CUDA.jl, pull requests merged in 2021-11, with the labels that each got.

#1232 Update introduction.jl
  docs/src/tutorials/introduction.jl
Labels: documentation

#1237 Avoid double-initializing partial accumulate results.
  src/accumulate.jl
  test/array.jl
Labels: bugfix

#1239 Bump CUTENSOR and fix on CUDA 11.5
  Artifacts.toml
Labels: cuda libraries

#1243 Optimize CUTENSOR contraction.
  lib/cutensor/wrappers.jl
  lib/utils/call.jl
Labels: cuda libraries

#1245 Don't use nondeterministic atomics in dot when requested.
  src/linalg.jl
  test/linalg.jl
Labels: enhancement

#1246 Remove CUBLAS decomposition tests without pivoting.
  test/cublas.jl
Labels: cuda libraries

#1217 Add bitonic sort implementation
  src/sorting.jl
  test/sorting.jl
Labels: enhancement, cuda array
