Repository JuliaGPU/CUDA.jl, pull requests merged in 2021-04, with the labels that each got.

#801 Various improvements
  Manifest.toml
  deps/compatibility.jl
  src/compiler/gpucompiler.jl
  src/device/intrinsics/indexing.jl
  src/device/intrinsics/warp_shuffle.jl
  test/device/intrinsics.jl
Labels: cuda kernels, enhancement

#788 Speed-up rand: Tausworthe RNG with shared random state.
  .buildkite/pipeline.yml
  perf/kernel.jl
  src/CUDA.jl
  src/compiler/execution.jl
  src/device/intrinsics.jl
  src/device/intrinsics/random.jl
  src/device/random.jl
  src/random.jl
  test/device/intrinsics.jl
  test/device/random.jl
  test/runtests.jl
Labels: cuda kernels, performance

#804 Speed-up view boundscheck.
  src/array.jl
Labels: performance

#805 Don't use mod from libdevice.
  src/device/intrinsics/math.jl
  test/device/intrinsics.jl
Labels: bugfix, cuda kernels

#806 fix bounds check for reverse kwarg and add tests
  src/reverse.jl
  test/array.jl
Labels: bugfix, cuda array

#811 Fix detection of need-for-cudadevrt.
  src/compiler/execution.jl
Labels: bugfix

#818 More OOM fixes for the stream-ordered allocator
  .buildkite/pipeline.yml
  lib/cudadrv/module.jl
  src/pool.jl
  src/pool/none.jl
Labels: bugfix, cuda array, cuda libraries

#827 Test validation of GPU-only function.
  Manifest.toml
  Project.toml
  test/device/intrinsics.jl
Labels: tests

#835 Add an integration benchmark.
  perf/Manifest.toml
  perf/Project.toml
  perf/runbenchmarks.jl
  perf/volumerhs.jl
Labels: ci, performance

#840 Only synchronize the REPL when CUDA is configured.
  src/initialization.jl
Labels: bugfix

#845 Sorting perf (again)
  src/sorting.jl
Labels: cuda array, performance

#842 @atomic support * and /
  src/device/intrinsics/atomics.jl
  test/device/intrinsics.jl
Labels: cuda kernels, enhancement, needs tests

#847 Remove extraneous apostrophe
  docs/src/installation/conditional.md
Labels: documentation

#853 reduce_block fixes.
  src/mapreduce.jl
Labels: performance

#854 Fix sorting large arrays.
  src/sorting.jl
  test/sorting.jl
Labels: bugfix, cuda array

#857 Identify the buffer during unsafe_wrap to support unified free.
  src/array.jl
Labels: cuda array

#844 CUDNN docstring revisions.
  lib/cudnn/CUDNN.jl
  lib/cudnn/activation.jl
  lib/cudnn/convolution.jl
  lib/cudnn/multiheadattn.jl
  lib/cudnn/normalization.jl
  lib/cudnn/optensor.jl
  lib/cudnn/pooling.jl
  lib/cudnn/reduce.jl
  lib/cudnn/rnn.jl
  lib/cudnn/softmax.jl
Labels: cuda libraries, documentation

#867 Improve multitasking with CUFFT.
  lib/cufft/fft.jl
Labels: cuda libraries, enhancement

#868 Introduce a HandleCache type.
  lib/cublas/CUBLAS.jl
  lib/cudnn/CUDNN.jl
  lib/curand/CURAND.jl
  lib/cusolver/CUSOLVER.jl
  lib/cusparse/CUSPARSE.jl
  lib/cutensor/CUTENSOR.jl
  lib/utils/APIUtils.jl
  lib/utils/cache.jl
Labels: cuda libraries, enhancement

#869 Improve multitasking with CURAND
  lib/cufft/fft.jl
  lib/curand/CURAND.jl
  lib/curand/random.jl
Labels: cuda libraries, enhancement

#858 Add support for CUDA 11.3.
  .buildkite/pipeline.yml
  Artifacts.toml
  deps/bindeps.jl
  deps/discovery.jl
  src/state.jl
  test/examples.jl
  test/exceptions.jl
  test/initialization.jl
  test/setup.jl
Labels: cuda libraries

#873 fix #848: CUDNN convolution incorrect for small images
  lib/cudnn/convolution.jl
Labels: bugfix, cuda libraries

#871 Half-Precision Intrinsics
  src/device/intrinsics/atomics.jl
  src/device/intrinsics/math.jl
  src/device/intrinsics/warp_shuffle.jl
  test/device/intrinsics.jl
Labels: cuda kernels, enhancement

#509 Implement statistics functions: correlation and covariance
  src/statistics.jl
  test/statistics.jl
Labels: cuda array, enhancement
