Repository JuliaGPU/CUDA.jl, pull requests merged in 2021-03, with the labels that each got.

#740 Don't error out if failing to parse the local CUDA version.
  deps/bindeps.jl
  deps/discovery.jl
Labels: installation

#739 fix testmode batchnorm back
  lib/cudnn/batchnorm.jl
  test/cudnn/nnlib.jl
Labels: backport, bugfix

#743 Add back an older artifact for CUDNN on PPC with CUDA 10.2.
  Artifacts.toml
Labels: installation

#756 Fix cuda-memcheck, don't use memory pools.
  lib/cudadrv/memory.jl
  test/cudnn/convolution.jl
Labels: ci

#749 Test sort with at-test at the toplevel, for better reporting.
  test/sorting.jl
Labels: ci

#759 Update generated wrappers
  lib/cublas/libcublas_common.jl
  lib/cudadrv/libcuda_common.jl
  lib/cudnn/libcudnn_common.jl
  lib/cufft/libcufft_common.jl
  lib/curand/libcurand_common.jl
  lib/cusolver/libcusolver.jl
  lib/cusolver/libcusolver_common.jl
  lib/cusparse/libcusparse.jl
  lib/cusparse/libcusparse_common.jl
  lib/cutensor/libcutensor_common.jl
  res/wrap/Manifest.toml
  res/wrap/Project.toml
  res/wrap/patches/cudadrv/batched_memop.patch
  res/wrap/wrap.jl
Labels: cuda libraries

#760 Rework memory pinning and speed up async ops on unpinned memory
  lib/cudadrv/memory.jl
  lib/utils/APIUtils.jl
  lib/utils/threading.jl
  src/array.jl
  src/pool/binned.jl
  src/pool/none.jl
  src/pool/simple.jl
  src/pool/split.jl
  src/pool/utils.jl
  test/cudadrv/memory.jl
Labels: cuda array, enhancement

#761 Improve context switching
  docs/src/usage/multigpu.md
  lib/cudadrv/context.jl
  lib/cudadrv/events.jl
  lib/cudadrv/memory.jl
  lib/cudadrv/module.jl
  lib/cudadrv/module/linker.jl
  lib/cudadrv/pool.jl
  lib/cudadrv/stream.jl
  lib/curand/random.jl
  src/array.jl
  src/pool.jl
  src/pool/binned.jl
  src/pool/none.jl
  src/pool/simple.jl
  src/pool/split.jl
  src/state.jl
  src/texture.jl
  test/cudadrv/module.jl
  test/cudadrv/pool.jl
  test/cutensor/contractions.jl
  test/cutensor/elementwise_binary.jl
  test/cutensor/elementwise_trinary.jl
  test/execution.jl
  test/initialization.jl
  test/pool.jl
  test/runtests.jl
  test/setup.jl
Labels: bugfix, cuda libraries, enhancement

#766 Docs on multitasking
  .github/workflows/PreviewPagesCleanup.yml
  docs/Manifest.toml
  docs/Project.toml
  docs/make.jl
  docs/src/index.md
  docs/src/installation/overview.md
  docs/src/lib/driver.md
  docs/src/usage/array.md
  docs/src/usage/multigpu.md
  docs/src/usage/multitasking.md
  docs/src/usage/multitasking/tasks.png
  docs/src/usage/multitasking/tasks_pinned.png
  lib/cudadrv/stream.jl
  src/device/intrinsics/wmma.jl
  src/indexing.jl
Labels: documentation

#768 Update to CUDA 11.2 Update 2.
  Artifacts.toml
  deps/bindeps.jl
  deps/discovery.jl
  lib/cublas/libcublas_common.jl
  lib/cufft/libcufft_common.jl
  lib/curand/libcurand_common.jl
  lib/cusolver/libcusolver_common.jl
  lib/cusparse/libcusparse_common.jl
  lib/nvml/libnvml.jl
  lib/nvml/libnvml_common.jl
  res/wrap/Manifest.toml
  res/wrap/patches/cusolver/cppversion.patch
Labels: installation

#750 Use contextual dispatch for device functions.
  Manifest.toml
  Project.toml
  deps/compatibility.jl
  examples/wmma/high-level.jl
  examples/wmma/low-level.jl
  src/CUDA.jl
  src/accumulate.jl
  src/array.jl
  src/broadcast.jl
  src/compiler/execution.jl
  src/compiler/gpucompiler.jl
  src/device/intrinsics.jl
  src/device/intrinsics/math.jl
  src/forwarddiff.jl
  src/initialization.jl
  src/mapreduce.jl
  src/sorting.jl
  test/Project.toml
  test/broadcast.jl
  test/device/intrinsics.jl
  test/exceptions.jl
  test/execution.jl
  test/forwarddiff.jl
  test/runtests.jl
Labels: cuda kernels, enhancement, needs tests

#778 Don't free memory asynchronously from finalizers.
  lib/cudadrv/CUDAdrv.jl
  src/array.jl
  src/pool.jl
  src/pool/binned.jl
  src/pool/none.jl
  src/pool/simple.jl
  src/pool/split.jl
Labels: cuda array

#762 Quicksort performance update
  src/sorting.jl
  test/sorting.jl
Labels: cuda array, performance

#308 cuSolverMg wrappers
  deps/bindeps.jl
  deps/discovery.jl
  lib/cusolver/CUSOLVER.jl
  lib/cusolver/base.jl
  lib/cusolver/dense.jl
  lib/cusolver/libcusolver.jl
  lib/cusolver/libcusolver_common.jl
  lib/cusolver/multigpu.jl
  lib/cusolver/sparse.jl
  res/wrap/wrap.jl
  test/cusolver/dense.jl
  test/cusolver/multigpu.jl
  test/cusolver/sparse.jl
  test/runtests.jl
Labels: cuda libraries, enhancement, tests

#779 Set exception flag asynchronously.
  lib/cudadrv/module/global.jl
  src/compiler/exceptions.jl
Labels: cuda libraries

#772 Add a basic implementation of rand() for use inside kernels
  Manifest.toml
  Project.toml
  src/CUDA.jl
  src/array.jl
  src/compiler/execution.jl
  src/device/intrinsics.jl
  src/device/intrinsics/random.jl
  test/device/intrinsics.jl
Labels: cuda kernels, enhancement

#792 Optimize array construction and allocation
  lib/cudadrv/memory.jl
  lib/cufft/fft.jl
  src/array.jl
  src/pool.jl
  src/state.jl
Labels: performance

#795 Don't use the stream-ordered memory pool for PR benchmarks.
  .buildkite/pipeline.yml
Labels: ci
