Repository JuliaGPU/CUDA.jl, pull requests merged in 2021-01, with the labels that each got.

#620 Test with the 1.6 nightly, not 1.7.
  .buildkite/pipeline.yml
Labels: ci

#608 Fixes wrong spacing in docstring admonition
  src/device/intrinsics/synchronization.jl
Labels: documentation

#604 Fix wrong initialisation error message
  src/initialization.jl
Labels: bugfix

#618 Fix broadcasting with Base.angle
  src/broadcast.jl
Labels: performance

#622 Initial compatibility with CUDA 11.2.
  deps/compatibility.jl
  deps/discovery.jl
Labels: installation

#625 cudaconvert captured values in closures.
  Manifest.toml
  src/compiler/execution.jl
  test/execution.jl
Labels: cuda kernels, enhancement

#639 Bump artifacts for Windows/Julia 1.6 compatibility.
  Artifacts.toml
Labels: installation

#640 Bump Reexport to 1.0
  Manifest.toml
  Project.toml
Labels: dependencies

#642 README: add some information on viewing capabilities of your devices
  README.md
Labels: documentation

#645 Remove duplicate functions.
  lib/nvml/libnvml_deprecated.jl
Labels: backport

#646 Use released version of Adapt.jl
  Manifest.toml
  Project.toml
Labels: dependencies

#647 Simplify list of tests to skip.
  test/runtests.jl
Labels: ci

#649 Use raw output for CUBLAS log message.
  lib/cublas/CUBLAS.jl
Labels: bugfix, cuda libraries

#652 Allow running benchmarks outside of the master branch on other systems.
  .buildkite/pipeline.yml
Labels: ci

#653 Bump GPUCompiler.
  Manifest.toml
  test/codegen.jl
Labels: cuda kernels, performance

#655 Run the tests from the current directory.
  test/runtests.jl
Labels: tests

#654 Reuse the compiler when generating SASS code.
  src/compiler/reflection.jl
  test/codegen.jl
Labels: cuda kernels

#663 Support view on unmanaged arrays.
  src/array.jl
  test/array.jl
Labels: bugfix, cuda array

#665 Retry CuModule creation when OOM.
  lib/cudadrv/module.jl
  src/pool.jl
Labels: cuda libraries, enhancement

#431 CUDA quicksort
  perf/array.jl
  src/CUDA.jl
  src/device/array.jl
  src/device/intrinsics/dynamic_parallelism.jl
  src/device/intrinsics/output.jl
  src/sorting.jl
  test/Project.toml
  test/sorting.jl
Labels: cuda array, enhancement

#669 Make fill async.
  src/array.jl
Labels: cuda array, performance

#671 Fix version lookups.
  lib/cublas/CUBLAS.jl
  lib/cudadrv/context/primary.jl
Labels: backport, bugfix

#674 Protect the kernel closure from GC collection.
  src/compiler/execution.jl
Labels: bugfix

#662 Automatic task-based concurrency using local streams
  lib/cublas/CUBLAS.jl
  lib/cublas/error.jl
  lib/cudadrv/context.jl
  lib/cudadrv/error.jl
  lib/cudadrv/events.jl
  lib/cudadrv/execution.jl
  lib/cudadrv/libcuda.jl
  lib/cudadrv/memory.jl
  lib/cudadrv/stream.jl
  lib/cudnn/CUDNN.jl
  lib/cudnn/error.jl
  lib/cufft/CUFFT.jl
  lib/cufft/error.jl
  lib/cufft/fft.jl
  lib/cupti/error.jl
  lib/curand/CURAND.jl
  lib/curand/error.jl
  lib/curand/random.jl
  lib/cusolver/CUSOLVER.jl
  lib/cusolver/error.jl
  lib/cusparse/CUSPARSE.jl
  lib/cusparse/error.jl
  lib/cutensor/CUTENSOR.jl
  lib/cutensor/error.jl
  lib/cutensor/wrappers.jl
  res/wrap/wrap.jl
  src/array.jl
  src/initialization.jl
  src/pool.jl
  src/precompile.jl
  src/state.jl
  src/utilities.jl
  test/cudadrv/context.jl
  test/cudadrv/events.jl
  test/cudadrv/execution.jl
  test/cudadrv/memory.jl
  test/cudadrv/stream.jl
  test/cufft.jl
  test/exceptions.jl
  test/initialization.jl
  test/setup.jl
Labels: cuda kernels, cuda libraries, enhancement
