Repository JuliaGPU/CUDA.jl, pull requests merged in 2021-05, with the labels that each got.

#881 Support unsigned inputs to integer intrinsics.
  src/device/intrinsics/math.jl
  src/device/llvm.jl
Labels: bugfix, cuda kernels

#880 Support for printing tuples.
  src/device/intrinsics/output.jl
  test/device/intrinsics.jl
Labels: cuda kernels, enhancement

#877 Add wrappers for the CUDA graph API.
  lib/cudadrv/CUDAdrv.jl
  lib/cudadrv/graph.jl
  test/cudadrv/graph.jl
Labels: cuda libraries, enhancement

#882 Switch to Philox2x32 for device-side RNG
  Manifest.toml
  Project.toml
  src/device/random.jl
  src/random.jl
Labels: cuda kernels, enhancement

#886 Treat CartesianIndices in views as scalars.
  src/array.jl
  test/array.jl
Labels: cuda array

#889 Update artifacts and use sources from unified JLLs.
  .buildkite/pipeline.yml
  Artifacts.toml
  deps/bindeps.jl
  lib/cudnn/libcudnn.jl
  lib/cudnn/libcudnn_common.jl
  lib/cudnn/libcudnn_deprecated.jl
  lib/cutensor/libcutensor_common.jl
  lib/cutensor/wrappers.jl
  res/wrap/Manifest.toml
  res/wrap/Project.toml
  res/wrap/patches/cudnn/algorithm.patch
  res/wrap/wrap.jl
  src/initialization.jl
Labels: cuda libraries

#890 Lazy initialization of CUDNN and CUTENSOR
  deps/bindeps.jl
  src/initialization.jl
Labels: cuda libraries

#900 Make cusolvermg really optional.
  deps/bindeps.jl
Labels: cuda libraries

#902 Take back control over the CUFFT work area.
  lib/cufft/fft.jl
Labels: cuda libraries

#908 Split test for better parallelization.
  Manifest.toml
  test/device/intrinsics.jl
  test/device/intrinsics/atomics.jl
  test/device/intrinsics/math.jl
  test/device/intrinsics/memory.jl
  test/device/intrinsics/output.jl
  test/device/intrinsics/wmma.jl
  test/runtests.jl
Labels: tests

#907 Add Windows CI.
  .buildkite/pipeline.yml
  lib/cublas/wrappers.jl
  lib/cudadrv/memory.jl
  src/pool.jl
  test/cudadrv/memory.jl
  test/cudnn/rnn.jl
  test/device/intrinsics/output.jl
Labels: ci

#898 Rework timings
  Project.toml
  deps/bindeps.jl
  src/CUDA.jl
  src/compiler/execution.jl
  src/initialization.jl
  src/pool.jl
  src/pool/binned.jl
  src/pool/none.jl
  src/pool/simple.jl
  src/pool/split.jl
  src/pool/utils.jl
  test/Project.toml
  test/runtests.jl
  test/setup.jl
Labels: ci, performance

#904 Fix #849, allow CUSPARSE to use F16
  lib/cublas/linalg.jl
  lib/cublas/wrappers.jl
  lib/cusparse/conversions.jl
  lib/cusparse/generic.jl
  lib/cusparse/interfaces.jl
  test/cublas.jl
  test/cusparse.jl
Labels: cuda libraries, needs tests

#911 Just some missing tests for CUBLAS
  test/cublas.jl
Labels: cuda libraries, tests

#921 Fix update of CUFFT handle.
  lib/cufft/fft.jl
Labels: cuda libraries

#924 Use multiple GPUs on CI when available.
  test/runtests.jl
Labels: ci

#925 Fix two-step mapreduce with wrapped output.
  src/mapreduce.jl
  test/array.jl
Labels: bugfix, cuda array

#927 Eagerly free the CUFFT workspace when generating a new one.
  lib/cufft/fft.jl
Labels: cuda libraries

#931 Fix the REPL synchronization hook.
  src/initialization.jl
Labels: bugfix

#930 Fix CUDA.function without throwing.
  src/initialization.jl
Labels: bugfix

#913 Fix bug and add tests for iamax/iamin
  lib/cublas/wrappers.jl
  test/cublas.jl
Labels: bugfix, cuda libraries, tests

#932 Re-initialize the random seed every time.
  src/compiler/execution.jl
  src/device/random.jl
Labels: bugfix, ci

#892 Compile using the toolkit, not the driver.
  Manifest.toml
  deps/bindeps.jl
  src/compiler/execution.jl
  test/execution.jl
Labels: cuda kernels

#936 Implement CUDA's Enhanced Compatibility when selecting a toolkit.
  .buildkite/pipeline.yml
  deps/bindeps.jl
  src/initialization.jl
Labels: installation
