Repository JuliaGPU/CUDA.jl, pull requests merged in 2021-02, with the labels that each got.

#691 Change to Buildkite v1 plugins.
  .buildkite/pipeline.yml
Labels: ci

#523 New high level interface for cuDNN
  lib/cudnn/CUDNN.jl
  lib/cudnn/README.md
  lib/cudnn/activation.jl
  lib/cudnn/batchnorm.jl
  lib/cudnn/compat.jl
  lib/cudnn/conv.jl
  lib/cudnn/convolution.jl
  lib/cudnn/descriptors.jl
  lib/cudnn/dropout.jl
  lib/cudnn/filter.jl
  lib/cudnn/inplace.jl
  lib/cudnn/libcudnn.jl
  lib/cudnn/multiheadattn.jl
  lib/cudnn/nnlib.jl
  lib/cudnn/normalization.jl
  lib/cudnn/optensor.jl
  lib/cudnn/pooling.jl
  lib/cudnn/reduce.jl
  lib/cudnn/rnn.jl
  lib/cudnn/softmax.jl
  lib/cudnn/tensor.jl
  lib/cudnn/util.jl
  test/cudnn.jl
  test/cudnn/activation.jl
  test/cudnn/convolution.jl
  test/cudnn/dropout.jl
  test/cudnn/inplace.jl
  test/cudnn/multiheadattn.jl
  test/cudnn/nnlib.jl
  test/cudnn/normalization.jl
  test/cudnn/optensor.jl
  test/cudnn/pooling.jl
  test/cudnn/reduce.jl
  test/cudnn/rnn.jl
  test/cudnn/softmax.jl
  test/cudnn/tensor.jl
  test/forwarddiff.jl
Labels: cuda libraries, enhancement

#682 Add fast getri_strided_batch
  lib/cublas/wrappers.jl
  test/cublas.jl
Labels: cuda libraries

#694 Fix exception flag linkage for linking.
  src/device/runtime.jl
Labels: bugfix, cuda kernels

#680 Support an additional nvdisasm version.
  deps/discovery.jl
Labels: installation

#693 CUPTI improvements for multithreading
  lib/cupti/error.jl
  src/compiler/reflection.jl
Labels: bugfix, cuda libraries

#698 fix bug in CURAND.jl's set_stream function.
  lib/curand/CURAND.jl
Labels: bugfix

#703 Remove special-cased algorithm selection for CUDNN convolution
  lib/cudnn/convolution.jl
Labels: bugfix, cuda libraries

#704 Keep track of active handles to avoid early collection.
  lib/cublas/CUBLAS.jl
  lib/cudnn/CUDNN.jl
  lib/curand/CURAND.jl
  lib/cusolver/CUSOLVER.jl
  lib/cusparse/CUSPARSE.jl
  lib/cutensor/CUTENSOR.jl
  lib/utils/call.jl
Labels: bugfix, cuda libraries

#636 bilinear upsampling
  LICENSE.md
  src/nnlib.jl
  test/nnlib.jl
Labels: cuda array, enhancement

#710 Make CUDNN tests eagerly invoke at-test for better error reporting.
  test/cudnn/activation.jl
  test/cudnn/convolution.jl
  test/cudnn/dropout.jl
  test/cudnn/inplace.jl
  test/cudnn/multiheadattn.jl
  test/cudnn/normalization.jl
  test/cudnn/optensor.jl
  test/cudnn/pooling.jl
  test/cudnn/reduce.jl
  test/cudnn/rnn.jl
  test/cudnn/softmax.jl
  test/cudnn/tensor.jl
Labels: ci

#712 Report JIT error log with linker errors.
  lib/cudadrv/module.jl
  lib/cudadrv/module/linker.jl
  test/cudadrv/module.jl
  test/setup.jl
Labels: cuda libraries, enhancement

#709 Support for cushow-ing multiple values, including LLVMPtrs.
  src/device/intrinsics/output.jl
  test/device/intrinsics.jl
Labels: cuda kernels, enhancement

#717 Flip exception_flag filter! predicate
  src/compiler/execution.jl
Labels: bugfix

#719 Upgrade CUDA 11.2 to Update 1.
  Artifacts.toml
  deps/bindeps.jl
  deps/discovery.jl
Labels: installation

#718 Keep some memory reserved for external allocations.
  src/pool.jl
  src/pool/binned.jl
  src/pool/none.jl
  src/pool/simple.jl
  src/pool/split.jl
Labels: cuda array

#723 Add support for and switch test to warp-synchrnous vote intrinsics.
  src/device/intrinsics/warp_vote.jl
  test/device/intrinsics.jl
Labels: bugfix

#729 Eagerly dlopen cublasLt to prevent a system library getting picked up.
  deps/bindeps.jl
Labels: bug, installation

#724 Specialize Base.to_index for AnyCuArray{Bool}
  src/indexing.jl
  test/array.jl
Labels: cuda array, enhancement

#732 Perform pool operations in the correct context.
  src/array.jl
Labels: bugfix

#679 Use CUDA 11.2's stream-ordered allocator
  .buildkite/pipeline.yml
  lib/cudadrv/CUDAdrv.jl
  lib/cudadrv/memory.jl
  lib/cudadrv/pool.jl
  src/pool.jl
  src/pool/binned.jl
  src/pool/none.jl
  src/pool/simple.jl
  src/pool/split.jl
  src/pool/utils.jl
  src/state.jl
  src/utilities.jl
  test/examples.jl
  test/exceptions.jl
  test/initialization.jl
  test/setup.jl
Labels: cuda array

#733 Streamline use of retry_reclaim.
  lib/cublas/error.jl
  lib/cublas/wrappers.jl
  lib/cudadrv/error.jl
  lib/cudnn/base.jl
  lib/cudnn/dropout.jl
  lib/cudnn/error.jl
  lib/cufft/CUFFT.jl
  lib/cufft/error.jl
  lib/cufft/fft.jl
  lib/cupti/CUPTI.jl
  lib/cupti/error.jl
  lib/curand/error.jl
  lib/curand/random.jl
  lib/curand/wrappers.jl
  lib/cusolver/error.jl
  lib/cusolver/wrappers.jl
  lib/cusparse/error.jl
  lib/cusparse/management.jl
  lib/cutensor/error.jl
  lib/nvml/error.jl
  src/CUDA.jl
  src/pool.jl
Labels: cuda array, enhancement

#734 Threading fixes
  lib/cudadrv/context.jl
  lib/cudadrv/stream.jl
  lib/curand/CURAND.jl
  src/pool.jl
  src/pool/utils.jl
  src/state.jl
  test/pool.jl
Labels: bugfix
