Repository JuliaGPU/CUDA.jl, pull requests merged in 2021-09, with the labels that each got.

#1134 Small improvements to discovery of local toolkits.
  deps/bindeps.jl
  deps/compatibility.jl
  deps/discovery.jl
  src/compiler/gpucompiler.jl
Labels: installation

#950 CI fixes
  .buildkite/pipeline.yml
  Manifest.toml
  Project.toml
  lib/cudadrv/execution.jl
  lib/cudnn/util.jl
  perf/volumerhs.jl
  src/compiler/execution.jl
  src/device/intrinsics/dynamic_parallelism.jl
  src/device/intrinsics/output.jl
  src/device/quirks.jl
  test/cublas.jl
  test/runtests.jl
  test/setup.jl
Labels: ci

#1151 Fix normalize on complex number
  lib/cublas/linalg.jl
  test/linalg.jl
Labels: bugfix, cuda libraries

#1147 Native device synchronization
  lib/cudadrv/context.jl
  lib/cudadrv/stream.jl
  src/initialization.jl
  test/cudadrv.jl
  test/setup.jl
Labels: cuda array, bugfix

#1146 Streamline the random number interface.
  lib/curand/random.jl
  src/random.jl
  test/random.jl
Labels: enhancement, cuda libraries

#1132 support transpose CSC to CUDA CSR
  lib/cusparse/array.jl
  lib/cusparse/conversions.jl
  test/cusparse/interfaces.jl
Labels: enhancement, needs tests, cuda libraries

#1159 Binary dependency changes
  deps/bindeps.jl
  deps/discovery.jl
  lib/cudadrv/version.jl
  src/utilities.jl
Labels: installation

#1153 Preserve Int32 hardware indices
  Manifest.toml
  examples/pairwise.jl
  examples/peakflops.jl
  examples/vadd.jl
  perf/byval.jl
  perf/kernel.jl
  src/accumulate.jl
  src/device/array.jl
  src/device/intrinsics/indexing.jl
  src/device/pointer.jl
  src/device/random.jl
  src/indexing.jl
  src/mapreduce.jl
  src/random.jl
  src/reverse.jl
  src/sorting.jl
  test/device/array.jl
  test/device/intrinsics.jl
  test/execution.jl
Labels: cuda kernels, performance

#1161 Bump dependencies.
  Manifest.toml
  Project.toml
Labels: dependencies

#1163 Generalize Sparse Array Indices Type in Struct Def
  lib/cusparse/array.jl
Labels: cuda libraries
