Repository JuliaGPU/CUDA.jl, pull requests merged in 2021-10, with the labels that each got.

#1135 Rework device and context getters.
  lib/cudadrv/context.jl
  lib/cudadrv/devices.jl
  lib/cudadrv/events.jl
  lib/cudadrv/graph.jl
  lib/cudadrv/memory.jl
  lib/cudadrv/module.jl
  lib/cudadrv/module/linker.jl
  lib/cudadrv/occupancy.jl
  lib/cudadrv/pool.jl
  lib/cudadrv/stream.jl
  src/array.jl
  src/compiler/exceptions.jl
  src/deprecated.jl
  src/state.jl
  test/array.jl
  test/cudadrv.jl
  test/initialization.jl
Labels: cuda array, cuda libraries

#1152 Addition and multiplication over cuarray and cusparse
  lib/cusparse/CUSPARSE.jl
  lib/cusparse/array.jl
  lib/cusparse/extra.jl
  lib/cusparse/interfaces.jl
  test/cusparse/interfaces.jl
Labels: cuda libraries

#1149 support interpret(reshape)
  src/array.jl
  test/array.jl
Labels: cuda array

#1174 Fix big mapreduce kernel for inputs without neutral element.
  src/mapreduce.jl
  test/array.jl
Labels: cuda array, bugfix

#1093 implement sparse
  lib/cusparse/conversions.jl
  test/cusparse/conversions.jl
Labels: bugfix, cuda libraries

#1182 Implement forward compatibility
  Artifacts.toml
  lib/cublas/CUBLAS.jl
  lib/cublas/error.jl
  lib/cublas/libcublas.jl
  lib/cublas/libcublas_deprecated.jl
  lib/cudadrv/CUDAdrv.jl
  lib/cudadrv/error.jl
  lib/cudadrv/libcuda.jl
  lib/cudadrv/libcuda_deprecated.jl
  lib/cudadrv/version.jl
  lib/cudnn/CUDNN.jl
  lib/cudnn/error.jl
  lib/cudnn/libcudnn.jl
  lib/cudnn/libcudnn_deprecated.jl
  lib/cufft/CUFFT.jl
  lib/cufft/error.jl
  lib/cufft/libcufft.jl
  lib/cupti/CUPTI.jl
  lib/cupti/error.jl
  lib/cupti/libcupti.jl
  lib/curand/CURAND.jl
  lib/curand/error.jl
  lib/curand/libcurand.jl
  lib/cusolver/CUSOLVER.jl
  lib/cusolver/error.jl
  lib/cusolver/libcusolver.jl
  lib/cusparse/CUSPARSE.jl
  lib/cusparse/error.jl
  lib/cusparse/libcusparse.jl
  lib/cusparse/libcusparse_deprecated.jl
  lib/cutensor/CUTENSOR.jl
  lib/cutensor/error.jl
  lib/cutensor/libcutensor.jl
  lib/nvml/NVML.jl
  lib/nvml/error.jl
  lib/nvml/libnvml.jl
  lib/nvml/libnvml_deprecated.jl
  lib/nvtx/NVTX.jl
  lib/nvtx/libnvtx.jl
  res/wrap/wrap.jl
  src/utilities.jl
Labels: installation

#1183 Bump GPUCompiler for 1.8 compat.
  Manifest.toml
Labels: dependencies

#1187 Update documentation
  docs/Manifest.toml
  docs/Project.toml
  docs/make.jl
  docs/src/api/essentials.md
  docs/src/api/kernel.md
  docs/src/lib/driver.md
  docs/src/usage/array.md
  lib/cudadrv/context.jl
  lib/cudadrv/devices.jl
  lib/cudadrv/graph.jl
  lib/cudadrv/stream.jl
  lib/cusparse/array.jl
  src/array.jl
  src/device/intrinsics/misc.jl
  src/device/intrinsics/synchronization.jl
  src/state.jl
Labels: documentation

#1186 Bump GPUArrays.
  Manifest.toml
Labels: dependencies
