Repository JuliaGPU/CUDA.jl, pull requests merged in 2022-01, with the labels that each got.

#1303 Store the array length next to its dimensions.
  src/device/array.jl
Labels: cuda kernels, performance

#1196 Allow sorting of tuples of numbers
  src/sorting.jl
  test/sorting.jl
Labels: enhancement, cuda array

#1310 Fix artifact-related issues
  .buildkite/pipeline.yml
  Artifacts.toml
Labels: installation

#1319 Use pointer to async_send directly instead of a wrapper function
  lib/cudadrv/execution.jl
Labels: bugfix

#1315 Add additional quirks.
  src/device/quirks.jl
  src/device/utils.jl
  test/execution.jl
Labels: enhancement, cuda kernels

#1327 Bump CUTENSOR, expose libcutensorMg.
  Artifacts.toml
  deps/bindeps.jl
Labels: installation

#1335 Properly detect a missing driver.
  lib/cudadrv/CUDAdrv.jl
Labels: bugfix

#1345 Optimize memoization helpers.
  lib/utils/memoization.jl
  lib/utils/threading.jl
  src/pool.jl
Labels: performance
