Repository JuliaGPU/CUDA.jl, pull requests merged in 2022-06, with the labels that each got.

#1534 Lower dmax for contraction tests
  test/cutensor/contractions.jl
Labels: cuda libraries, tests

#1532 `ldiv!` for LU Decomposition
  lib/cusolver/linalg.jl
  test/cusolver/dense.jl
Labels: enhancement, cuda libraries

#1539 Add a utility to download artifacts without a functional driver.
  .buildkite/pipeline.yml
  deps/bindeps.jl
  lib/cudadrv/error.jl
Labels: installation

#1544 Explicit tests for type conversion
  test/utils.jl
Labels: tests

#1536 Fix convolution algorithm search
  lib/cudnn/convolution.jl
Labels: bugfix, cuda libraries

#1553 Update Documenter key.
  .buildkite/pipeline.yml
Labels: ci
