Repository JuliaGPU/CUDA.jl, pull requests merged in 2022-07, with the labels that each got.

#1547 Wrap `cusolverRf.h` and `cusolverSp_LOWLEVEL_PREVIEW.h`
  lib/cusolver/libcusolver.jl
  lib/cusolver/libcusolver_common.jl
  res/wrap/wrap.jl
Labels: cuda libraries

#1558 Import factorisation internal types from LinearAlgebra
  lib/cusolver/linalg.jl
Labels: bugfix

#1561 add reshape for CuDeviceArray
  src/device/array.jl
  test/device/array.jl
Labels: enhancement, cuda kernels
