Repository JuliaGPU/CUDA.jl, pull requests merged in 2022-10, with the labels that each got.

#1611 [CUSPARSE] Interface generic routines
  lib/cusparse/conversions.jl
  lib/cusparse/generic.jl
  lib/cusparse/helpers.jl
  lib/cusparse/libcusparse.jl
  test/cusparse.jl
  test/cusparse/generic.jl
Labels: enhancement, cuda libraries

#1613 [CUSPARSE] Update sparse-sparse GEMM
  lib/cusparse/generic.jl
  test/cusparse.jl
  test/cusparse/generic.jl
Labels: enhancement, cuda libraries

#1617 Don't use isbitsunion to support structs of union types.
  src/array.jl
  src/device/array.jl
  src/device/intrinsics/memory_shared.jl
Labels: bugfix

#1619 Update CUDA artifacts to 11.7 Update 1.
  Artifacts.toml
  deps/bindeps.jl
Labels: installation

#1620 Update to CUDA 11.8
  .buildkite/pipeline.yml
  Artifacts.toml
  deps/bindeps.jl
  src/utilities.jl
  test/cusparse/generic.jl
Labels: installation

#1625 Bump BFloat16s.
  Manifest.toml
Labels: dependencies

#1627 Restore functionality of FastMath.sincos.
  src/device/intrinsics/math.jl
  test/device/intrinsics/math.jl
Labels: performance

#1632 [CUSPARSE] Add CuMatrix * CuSparseMatrix products
  lib/cusparse/generic.jl
  lib/cusparse/helpers.jl
  lib/cusparse/interfaces.jl
  lib/cusparse/types.jl
  test/cusparse/generic.jl
Labels: enhancement, cuda libraries

#1636 Update CUTENSOR to v1.6
  lib/cutensor/Project.toml
  lib/cutensor/src/CUTENSOR.jl
  lib/cutensor/src/libcutensor.jl
  lib/cutensor/src/libcutensor_common.jl
Labels: cuda libraries

#1638 Upgrade CUSTATEVEC to v1.1
  lib/custatevec/Project.toml
  lib/custatevec/src/CUSTATEVEC.jl
  lib/custatevec/src/error.jl
  lib/custatevec/src/libcustatevec.jl
  lib/custatevec/src/libcustatevec_common.jl
  lib/custatevec/src/statevec.jl
  lib/custatevec/src/types.jl
Labels: cuda libraries

#1647 [CUSPARSE] Add dot(CuSparseVector,CuVector) and vice-versa
  lib/cusparse/interfaces.jl
  test/cusparse/interfaces.jl
Labels: enhancement, cuda libraries

#1640 [CUSPARSE] Add CuSparseVector ± CuSparseVector
  lib/cusparse/extra.jl
  lib/cusparse/interfaces.jl
  test/cusparse/interfaces.jl
Labels: enhancement, cuda libraries

#1639 Upgrade CUTENSORNET to v1.1
  lib/cutensornet/Project.toml
  lib/cutensornet/src/CUTENSORNET.jl
  lib/cutensornet/src/error.jl
  lib/cutensornet/src/libcutensornet.jl
  lib/cutensornet/src/libcutensornet_common.jl
  lib/cutensornet/src/tensornet.jl
  lib/cutensornet/src/types.jl
  lib/cutensornet/test/Project.toml
  lib/cutensornet/test/runtests.jl
Labels: cuda libraries

#1648 [CUSPARSE] Add ldiv! for CuSparseMatrixCOO and geam for CuSparseMatrixCSC
  lib/cusparse/extra.jl
  lib/cusparse/interfaces.jl
  test/cusparse/interfaces.jl
Labels: enhancement, cuda libraries

#1652 Don't warn about the old JULIA_CUDA_USE_BINARYBUILDER env var when using preferences
  src/initialization.jl
Labels: installation

#1643 Fix #1641
  lib/cusparse/array.jl
  test/cusparse.jl
Labels: bugfix, cuda libraries

#1658 Discover the system driver when CUDA_Driver_jll isn't available.
  Manifest.toml
  src/CUDA.jl
  src/initialization.jl
Labels: installation

#1659 Preserve buffer type when adapting to CuArray.
  src/array.jl
  test/array.jl
Labels: cuda array, bugfix
