Repository JuliaGPU/CUDA.jl, pull requests merged in 2022-03, with the labels that each got.

#1119 Add Int8 WMMA Support
  src/device/intrinsics/wmma.jl
  test/device/intrinsics/wmma.jl
Labels: enhancement, cuda kernels

#1285 Wrap generic sparse-sparse GEMM
  lib/cusparse/generic.jl
  lib/cusparse/helpers.jl
  test/cusparse.jl
Labels: cuda libraries

#1416 CUTENSOR: axpy! and axpby! not mutating fixed
  lib/cutensor/interfaces.jl
  lib/cutensor/tensor.jl
  test/cutensor/elementwise_binary.jl
Labels: bugfix, cuda libraries
