Repository JuliaGPU/CUDA.jl, pull requests merged in 2022-05, with the labels that each got.

#1493 Docstring for `cu`
  src/array.jl
Labels: documentation

#1201 expose sparse mv/mm algo selection
  lib/cusparse/generic.jl
  test/cusparse/generic.jl
Labels: cuda libraries

#1466 support sparse opnorm
  lib/cusparse/CUSPARSE.jl
  lib/cusparse/linalg.jl
  test/cusparse/linalg.jl
Labels: cuda libraries

#1462 Always inspect the task-local context when verifying before freeing.
  lib/cufft/fft.jl
  src/pool.jl
Labels: bugfix

#1507 Update artifacts
  .buildkite/pipeline.yml
  Artifacts.toml
  deps/bindeps.jl
  deps/compatibility.jl
  lib/cudadrv/CUDAdrv.jl
Labels: installation

#1516 Add method for LinearAlgebra.opnorm2
  lib/cusolver/linalg.jl
  test/cusolver/dense.jl
Labels: enhancement, cuda libraries

#1517 Promote to common eltype in matrix division
  lib/cusolver/linalg.jl
  test/cusolver/dense.jl
Labels: enhancement, cuda libraries

#1518 Fix Box-Muller transformation for complex eltypes
  src/random.jl
  test/random.jl
Labels: cuda array, bugfix

#1530 Make sure instantiating RNGs doesn't affect the global CPU RNG.
  lib/curand/random.jl
  src/random.jl
  test/random.jl
Labels: bugfix
