Repository JuliaGPU/CUDA.jl, pull requests merged in 2022-02, with the labels that each got.

#1357 Make the default pool visible when doing P2P
  lib/cudadrv/memory.jl
  lib/cudadrv/pool.jl
Labels: performance

#1359 Fix resize of empty arrays.
  src/array.jl
  test/array.jl
Labels: bugfix

#1367 Implement (limited) broadcast of sparse arrays
  lib/cusparse/CUSPARSE.jl
  lib/cusparse/array.jl
  lib/cusparse/broadcast.jl
  lib/cusparse/conversions.jl
  lib/cusparse/device.jl
  lib/cusparse/generic.jl
  lib/cusparse/level1.jl
  lib/cusparse/level2.jl
  lib/cusparse/level3.jl
  lib/cusparse/preconditioners.jl
  src/CUDA.jl
  src/random.jl
  test/cusparse.jl
  test/cusparse/broadcast.jl
  test/cusparse/device.jl
Labels: enhancement, cuda array

#1380 General purpose broadcast for sparse CSR matrices.
  lib/cusparse/CUSPARSE.jl
  lib/cusparse/broadcast.jl
  test/cusparse/broadcast.jl
Labels: enhancement, cuda array

#1390 Implement sparse operations with UniformScaling using broadcast.
  lib/cusparse/broadcast.jl
  lib/cusparse/interfaces.jl
  test/cusparse/interfaces.jl
Labels: cuda array

#1401 Implement sparse broadcasting with CSC matrices.
  lib/cusparse/broadcast.jl
  lib/cusparse/interfaces.jl
  test/cusparse/broadcast.jl
  test/cusparse/interfaces.jl
Labels: enhancement, cuda array

#1400 support BFloat16 for atomic_cas
  src/device/intrinsics/atomics.jl
  test/device/intrinsics/atomics.jl
Labels: enhancement, cuda kernels
