Repository JuliaGPU/CUDA.jl, pull requests merged in 2022-12, with the labels that each got.

#1695 [CUSPARSE] Support kron with Diagonal arguments
  lib/cusparse/linalg.jl
  test/cusparse/linalg.jl
Labels: enhancement, cuda libraries

#1698 Re-introduce memory limits.
  docs/src/usage/memory.md
  src/pool.jl
Labels: enhancement

#1704 WMMA: Don't wrap fragments of size 1 in a struct.
  src/device/intrinsics/wmma.jl
Labels: bugfix
