Repository JuliaGPU/CUDA.jl, pull requests merged in 2023-09, with the labels that each got.

#1999 Add some performance tips to the documentation
  docs/make.jl
  docs/src/tutorials/performance.jl
Labels: documentation, needs changes

#2088 Improve PTX ISA selection
  src/compatibility.jl
  src/compiler/compilation.jl
  src/compiler/execution.jl
  src/device/runtime.jl
  src/utilities.jl
  test/core/device/intrinsics.jl
  test/core/execution.jl
Labels: enhancement, cuda kernels

#2095 Add a method inv(CuMatrix)
  lib/cusolver/linalg.jl
  test/libraries/cusolver/dense.jl
Labels: enhancement, cuda array

#2096 Add mul!(A, B, C) where B or C is a diagonal matrix
  lib/cublas/linalg.jl
  test/libraries/cublas.jl
Labels: enhancement, cuda array
