Repository JuliaGPU/CUDA.jl, pull requests merged in 2023-03, with the labels that each got.

#1742 Add support for CUDA 12.0.
  .buildkite/pipeline.yml
  Manifest.toml
  Project.toml
  README.md
  lib/cublas/libcublas.jl
  lib/cudadrv/graph.jl
  lib/cudadrv/libcuda.jl
  lib/cudadrv/libcuda_deprecated.jl
  lib/cupti/libcupti.jl
  lib/cusparse/CUSPARSE.jl
  lib/cusparse/array.jl
  lib/cusparse/conversions.jl
  lib/cusparse/generic.jl
  lib/cusparse/interfaces.jl
  lib/cusparse/level1.jl
  lib/cusparse/level2.jl
  lib/cusparse/level3.jl
  lib/cusparse/libcusparse.jl
  lib/cusparse/libcusparse_deprecated.jl
  lib/nvml/libnvml.jl
  res/wrap/Manifest.toml
  res/wrap/cublas.toml
  res/wrap/cuda.toml
  res/wrap/cudnn.toml
  res/wrap/cufft.toml
  res/wrap/cupti.toml
  res/wrap/curand.toml
  res/wrap/cusolver.toml
  res/wrap/cusparse.toml
  res/wrap/custatevec.toml
  res/wrap/cutensor.toml
  res/wrap/cutensornet.toml
  res/wrap/wrap.jl
  src/compatibility.jl
  src/initialization.jl
  test/cufft.jl
  test/cusparse.jl
  test/cusparse/broadcast.jl
  test/cusparse/conversions.jl
  test/cusparse/generic.jl
  test/cusparse/interfaces.jl
Labels: dependencies

#1793 Add support for CUDA 12.1
  .buildkite/pipeline.yml
  Manifest.toml
  Project.toml
  lib/cudadrv/libcuda.jl
  lib/cupti/libcupti.jl
  lib/nvml/libnvml.jl
  res/wrap/Manifest.toml
  test/cusparse/conversions.jl
Labels: installation

#1800 Follow `Array`'s behavior when initializing
  src/array.jl
  test/array.jl
Labels: cuda array

#1802 [CUSOLVER] Support A \ b for rectangular matrices
  lib/cusolver/linalg.jl
  test/cusolver/dense.jl
Labels: cuda libraries

#1794 [CUSPARSE] Interface color reordering
  lib/cusparse/CUSPARSE.jl
  lib/cusparse/reorderings.jl
  test/cusparse.jl
Labels: cuda libraries
