Repository JuliaGPU/CUDA.jl, pull requests merged in 2023-06, with the labels that each got.

#1935 Detect and complain about loading system libraries.
  src/initialization.jl
Labels: installation

#1937 Avoid stack overflow with eary OOM reporting.
  src/pool.jl
Labels: bugfix

#1951 Update GPUCompiler to fix unreachable control flow.
  Manifest.toml
  Project.toml
  lib/cudadrv/state.jl
  src/compiler/compilation.jl
Labels: cuda kernels

#1965 Add and fix some aqua tests
  Project.toml
  lib/cusparse/linalg.jl
  src/array.jl
  src/compatibility.jl
  src/device/intrinsics/wmma.jl
  test/Project.toml
  test/base/aqua.jl
Labels: enhancement, tests

#1941 [CUSPARSE] Improved support for UniformScaling ad Diagonal
  lib/cusparse/conversions.jl
  lib/cusparse/interfaces.jl
  test/libraries/cusparse/interfaces.jl
Labels: enhancement, cuda libraries

#1954 Allow StaticArray eltype in matmat{vec,mul}
  lib/cublas/linalg.jl
  test/libraries/cublas.jl
Labels: bugfix
