Repository JuliaGPU/CUDA.jl, pull requests merged in 2023-07, with the labels that each got.

#1993 Add vectorized cached loads
  src/device/pointer.jl
  test/core/device/ldg.jl
Labels: enhancement, cuda kernels

#1943 Check mathType only if not Float32
  lib/cudnn/src/convolution.jl
Labels: bug, help wanted, cuda libraries

#1981 Add wrappers for `gemv_batched!`
  lib/cublas/libcublas.jl
  lib/cublas/wrappers.jl
  res/wrap/cublas.toml
  test/libraries/cublas.jl
Labels: enhancement, cuda libraries

#1946 1.10 enablement
  .buildkite/pipeline.yml
  lib/cublas/linalg.jl
  lib/cusparse/interfaces.jl
  src/array.jl
  src/device/array.jl
  test/libraries/cusolver/dense.jl
Labels: enhancement
