Repository JuliaGPU/CUDA.jl, pull requests merged in 2023-04, with the labels that each got.

#1818 Allow but warn when testing on not fully-supported devices.
  lib/cudadrv/state.jl
  test/runtests.jl
Labels: tests

#1881 Guard the initialization-time CUDA driver check in a try/catch.
  src/initialization.jl
Labels: installation

#1872 Don't collect `AbstractQ` objects in tests
  lib/cusolver/linalg.jl
  test/cusolver/dense.jl
Labels: cuda array
