Repository JuliaGPU/CUDA.jl, pull requests merged in 2023-08, with the labels that each got.

#2025 Perform synchronization on a worker thread
  .gitignore
  LocalPreferences.toml
  lib/cudadrv/CUDAdrv.jl
  lib/cudadrv/context.jl
  lib/cudadrv/events.jl
  lib/cudadrv/state.jl
  lib/cudadrv/stream.jl
  lib/cudadrv/synchronization.jl
  lib/utils/memoization.jl
  lib/utils/threading.jl
  src/pool.jl
Labels: enhancement, performance

#2024 Add a native profiler.
  .buildkite/pipeline.yml
  Manifest.toml
  Project.toml
  docs/Manifest.toml
  docs/src/development/profiling.md
  docs/src/usage/array.md
  lib/cudadrv/CUDAdrv.jl
  lib/cudadrv/profile.jl
  lib/cupti/wrappers.jl
  src/CUDA.jl
  src/profile.jl
  test/base/aqua.jl
  test/core/cudadrv.jl
  test/core/profile.jl
  test/setup.jl
Labels: enhancement

#2029 When freeing memory, use the high-level device getter.
  src/pool.jl
Labels: bugfix

#2040 On CUDA 12.2, have the memory pool enforce hard memory limits.
  docs/src/usage/memory.md
  lib/cudadrv/pool.jl
  src/pool.jl
  test/core/cudadrv.jl
Labels: enhancement

#2030 Add support for @cuda fastmath
  Manifest.toml
  Project.toml
  src/compiler/execution.jl
  test/core/codegen.jl
Labels: enhancement

#2035 rand: seed kernels from the host.
  .buildkite/pipeline.yml
  src/compiler/compilation.jl
  src/compiler/execution.jl
  src/device/random.jl
  src/device/runtime.jl
  src/sorting.jl
Labels: bugfix

#2041 Delay all initialization errors until run time.
  src/initialization.jl
Labels: enhancement, installation

#2044 Update cuStateVec to cuQuantum 23.6.
  lib/custatevec/Project.toml
Labels: cuda libraries

#2005 Fix accumulate bug
  src/accumulate.jl
  test/base/array.jl
Labels: cuda array, bugfix, needs changes

#1948 Implement reverse lookup (Ptr->Tuple) for CUDNN descriptors.
  lib/cudnn/src/convolution.jl
Labels: enhancement, cuda libraries

#2043 Add support for NVTX events to the integrated profiler.
  Manifest.toml
  Project.toml
  lib/cupti/wrappers.jl
  src/CUDA.jl
  src/initialization.jl
  src/profile.jl
  test/Project.toml
  test/core/profile.jl
Labels: enhancement, cuda kernels

#2051 Make sortperm! resilient to type mismatches.
  src/sorting.jl
  test/base/sorting.jl
Labels: cuda array, bugfix

#2047 Add some more fastmath functions
  src/device/intrinsics/math.jl
Labels: cuda kernels, performance

#2058 Rework how local toolkits are selected.
  .buildkite/pipeline.yml
  Dockerfile
  LocalPreferences.toml
  Manifest.toml
  Project.toml
  docs/src/installation/overview.md
  lib/cudadrv/version.jl
  lib/cudnn/src/cuDNN.jl
  lib/custatevec/src/cuStateVec.jl
  lib/cutensor/src/cuTENSOR.jl
  lib/cutensornet/src/cuTensorNet.jl
  src/CUDA.jl
  src/initialization.jl
  src/utilities.jl
Labels: installation

#2063 Batched SVD added (gesvdjBatched and gesvdaStridedBatched)
  lib/cusolver/dense.jl
  lib/cusolver/linalg.jl
  test/libraries/cusolver/dense.jl
Labels: enhancement, cuda libraries
