Repository JuliaGPU/CUDA.jl, pull requests merged in 2023-05, with the labels that each got.

#1890 CUSOLVER: Fix workspace size passing.
  lib/cusolver/dense.jl
Labels: bugfix

#1900 Restrict number of test jobs based on available memory.
  test/runtests.jl
Labels: tests

#1917 cuDNN: only choose conv algorithms if they match descriptor mathType
  lib/cudnn/src/convolution.jl
Labels: bugfix, cuda libraries

#1915 Align variables in constant memory by 256 bit
  src/device/random.jl
Labels: cuda kernels

#1916 Add norm functions for 3 floats
  src/device/intrinsics/math.jl
Labels: cuda kernels
