Repository JuliaGPU/CUDA.jl, pull requests merged in 2024-10, with the labels that each got.

#2518 Added multiplication of transpose / adjoint matrices by diagonal matrices
  lib/cublas/linalg.jl
  test/libraries/cublas.jl
Labels: enhancement, cuda libraries, needs changes

#2527 CUTENSOR: Reduce amount of broadcasts compiled during tests.
  lib/cutensor/test/elementwise_binary.jl
  lib/cutensor/test/elementwise_trinary.jl
  lib/cutensor/test/reductions.jl
Labels: tests

#2528 CUBLAS: Don't use BLAS1 wrappers for strided arrays, only vectors.
  lib/cublas/linalg.jl
  lib/cublas/wrappers.jl
  test/base/linalg.jl
Labels: cuda libraries

#2532 Clarify the synchronize(ctx)/device_synchronize() docstrings
  lib/cudadrv/context.jl
Labels: documentation
