Repository JuliaGPU/CUDA.jl, pull requests merged in 2024-04, with the labels that each got.

#2310 [CUBLAS] Interface gemm_grouped_batched
  lib/cublas/libcublas.jl
  lib/cublas/wrappers.jl
  res/wrap/cublas.toml
  test/libraries/cublas.jl
Labels: enhancement, cuda libraries

#2308 sortperm with dims
  src/sorting.jl
  test/base/sorting.jl
Labels: enhancement, cuda array

#2309 [CUSOLVER] Fix the dispatch for syevd! and heevd!
  lib/cusolver/dense.jl
Labels: bugfix, cuda libraries

#2329 Diagnose kernel limits on launch failure.
  lib/cudadrv/execution.jl
  test/core/execution.jl
Labels: enhancement, cuda kernels

#2330 Work around a CUPTI bug in CUDA 12.4 Update 1.
  src/compiler/reflection.jl
  test/core/execution.jl
Labels: bugfix, cuda kernels

#2327 fix broadcast defaulting to Mem.Unified()
  src/broadcast.jl
  test/base/broadcast.jl
Labels: cuda array, bugfix

#2304 Consider running GC when allocating and synchronizing
  docs/src/lib/driver.md
  lib/cudadrv/memory.jl
  lib/cudadrv/synchronization.jl
  lib/cudnn/src/convolution.jl
  src/CUDA.jl
  src/deprecated.jl
  src/initialization.jl
  src/pool.jl
  src/utilities.jl
  test/core/cudadrv.jl
  test/runtests.jl
Labels: enhancement, cuda array

#2335 Refactor memory wrappers
  Project.toml
  docs/Manifest.toml
  docs/src/development/debugging.md
  docs/src/development/kernel.md
  docs/src/lib/driver.md
  docs/src/usage/array.md
  docs/src/usage/memory.md
  docs/src/usage/multitasking.md
  lib/cudadrv/devices.jl
  lib/cudadrv/error.jl
  lib/cudadrv/execution.jl
  lib/cudadrv/libcuda.jl
  lib/cudadrv/memory.jl
  lib/cudadrv/module.jl
  lib/cudadrv/module/global.jl
  lib/cudadrv/state.jl
  lib/cudadrv/stream.jl
  lib/cudnn/Project.toml
  lib/custatevec/Project.toml
  lib/cutensor/Project.toml
  lib/cutensor/src/types.jl
  lib/utils/threading.jl
  src/CUDA.jl
  src/CUDAKernels.jl
  src/array.jl
  src/broadcast.jl
  src/compiler/exceptions.jl
  src/compiler/execution.jl
  src/deprecated.jl
  src/device/runtime.jl
  src/device/texture.jl
  src/initialization.jl
  src/iterator.jl
  src/memory.jl
  src/texture.jl
  test/base/array.jl
  test/core/cudadrv.jl
  test/core/initialization.jl
  test/core/pointer.jl
  test/core/pool.jl
  test/runtests.jl
Labels: enhancement, cuda array, speculative

#2342 Improve exception output
  ext/StaticArraysExt.jl
  src/compiler/exceptions.jl
  src/compiler/execution.jl
  src/device/quirks.jl
  src/device/runtime.jl
  test/base/exceptions.jl
Labels: enhancement, cuda kernels

#2348 Test multigpu on CI
  .buildkite/pipeline.yml
  lib/cudadrv/context.jl
  lib/cudadrv/memory.jl
  src/array.jl
  src/memory.jl
  test/runtests.jl
Labels: ci

#2346 Rework context handling
  lib/cudadrv/context.jl
  lib/cudadrv/devices.jl
  lib/cudadrv/libcuda.jl
  lib/cudadrv/memory.jl
  lib/cudadrv/module/global.jl
  lib/cudadrv/state.jl
  lib/cudadrv/stream.jl
  lib/cudadrv/version.jl
  lib/cupti/error.jl
  lib/cupti/wrappers.jl
  lib/nvml/libnvml.jl
  lib/utils/call.jl
  res/wrap/cuda.toml
  res/wrap/libcuda_prologue.jl
  res/wrap/libnvml_prologue.jl
  src/array.jl
  src/initialization.jl
  src/memory.jl
  src/profile.jl
  test/base/exceptions.jl
  test/core/cudadrv.jl
  test/core/initialization.jl
  test/runtests.jl
  test/setup.jl
Labels: enhancement, cuda libraries, performance
