Repository JuliaGPU/CUDA.jl, pull requests merged in 2024-05, with the labels that each got.

#2358 Suggest use of 32 bit types over 64 instead of just Float32 over Float64 [skip ci]
  docs/src/tutorials/performance.jl
Labels: documentation

#1869 Add Enzyme Forward mode custom rule
  ext/EnzymeCoreExt.jl
  test/Project.toml
  test/libraries/enzyme.jl
Labels: upstream

#2363 Return the currect memory type when wrapping system memory.
  src/array.jl
  test/base/array.jl
Labels: enhancement, cuda array

#2369 Enzyme: Forward mode sync
  ext/EnzymeCoreExt.jl
Labels: extensions

#2378 Add note about --check-bounds=yes
  docs/src/tutorials/performance.jl
Labels: documentation

#2374 Tegra support with artifacts
  Project.toml
  README.md
  lib/cudnn/Project.toml
  lib/custatevec/Project.toml
  lib/cutensor/Project.toml
  lib/cutensornet/Project.toml
  src/compatibility.jl
  src/compiler/compilation.jl
  src/initialization.jl
  src/utilities.jl
  test/Project.toml
  test/runtests.jl
Labels: installation

#2379 Test Enzyme in a separate CI job.
  .buildkite/pipeline.yml
  test/Project.toml
  test/extensions/enzyme.jl
  test/runtests.jl
Labels: extensions

#2381 Fix tests for Tegra.
  lib/cudadrv/memory.jl
  src/array.jl
  test/base/array.jl
  test/core/cudadrv.jl
Labels: tests

#2391 CUBLAS: Make sure CUBLASLt wrappers use the correct library.
  Project.toml
  lib/cublas/CUBLAS.jl
  lib/cublas/libcublas.jl
  lib/cublas/libcublasLt.jl
  res/wrap/cublas.toml
  res/wrap/cublasLt.toml
  res/wrap/wrap.jl
Labels: bugfix, cuda libraries

#2390 Fixes for Julia 1.12 / LLVM 17
  src/compiler/compilation.jl
  src/device/intrinsics/cooperative_groups.jl
  src/device/intrinsics/output.jl
  src/device/intrinsics/wmma.jl
Labels: enhancement

#2386 Enzyme: allocation functions
  ext/EnzymeCoreExt.jl
  test/extensions/enzyme.jl
Labels: extensions

#2392 Support CUDA 12.5
  .buildkite/pipeline.yml
  Project.toml
  README.md
  lib/cudadrv/libcuda.jl
  lib/cupti/wrappers.jl
  res/wrap/Manifest.toml
  src/compatibility.jl
  src/compiler/reflection.jl
  src/initialization.jl
  test/core/codegen.jl
  test/core/execution.jl
Labels: dependencies

#2396 Update Julia wrappers for CUDA v12.5
  lib/cublas/libcublas.jl
  lib/cudadrv/libcuda.jl
  lib/cufft/libcufft.jl
  lib/cupti/libcupti.jl
  lib/cusolver/libcusolver.jl
  lib/nvml/libnvml.jl
  res/wrap/Manifest.toml
  res/wrap/nvml.toml
Labels: enhancement, cuda libraries

#2398 Enable correct pool access for cublasXt.
  lib/cublas/CUBLAS.jl
  lib/cudadrv/pool.jl
Labels: bugfix, cuda libraries

#2399 More fine-grained CUPTI version checks.
  lib/cupti/wrappers.jl
  src/compiler/reflection.jl
  test/core/codegen.jl
  test/core/execution.jl
Labels: enhancement, cuda libraries

#2395 Mark cuarray as noalias
  Project.toml
  ext/EnzymeCoreExt.jl
  test/extensions/enzyme.jl
Labels: dependencies

#2402 Fix and test the legacy memory pool.
  .buildkite/pipeline.yml
  Project.toml
  src/memory.jl
Labels: cuda array, bugfix

#2403 add two quirks for rationals
  src/device/quirks.jl
  test/base/broadcast.jl
Labels: cuda array, bugfix

#2404 Bump cuDNN
  .buildkite/pipeline.yml
  lib/cudnn/Project.toml
  lib/cudnn/src/libcudnn.jl
  res/wrap/Manifest.toml
Labels: enhancement, cuda libraries
