Repository JuliaGPU/CUDA.jl, pull requests merged in 2024-11, with the labels that each got.

#2538 Removed allocations for transpose/adjoint - diagonal multiplications
  lib/cublas/linalg.jl
Labels: enhancement, cuda libraries

#2543 Fix formatting in profiling docs page
  docs/src/development/profiling.md
Labels: documentation

#2541 Consistent use of Nsight Compute
  docs/src/development/profiling.md
Labels: documentation

#2556 [CUSOLVER] Fix Xgesvdr!
  lib/cusolver/dense_generic.jl
  test/libraries/cusolver/dense_generic.jl
Labels: cuda libraries
