Repository JuliaGPU/CUDA.jl, pull requests merged in 2024-09, with the labels that each got.

#2495 CUSPARSE: Fix sparse constructor with duplicate elements.
  lib/cusparse/conversions.jl
  test/libraries/cusparse.jl
Labels: bugfix, cuda libraries

#2416 Add kernel compilation requirements to docs
  docs/src/development/kernel.md
Labels: documentation

#2465 CUSOLVER (dense): cache workspace in fat handle
  lib/cusolver/CUSOLVER.jl
  lib/cusolver/dense.jl
  lib/cusolver/dense_generic.jl
Labels: enhancement, cuda libraries

#2472 Re-use pre-converted kernel arguments when launching kernels.
  src/compiler/execution.jl
Labels: performance, speculative

#2490 Enzyme: adapt to pending version breaking update
  .buildkite/pipeline.yml
  Project.toml
  ext/EnzymeCoreExt.jl
  test/extensions/enzyme.jl
Labels: extensions
