Repository JuliaGPU/CUDA.jl, pull requests merged in 2024-03, with the labels that each got.

#2279 Cached workspace prototype for custatevec
  lib/cusolver/dense.jl
  lib/cusparse/generic.jl
  lib/custatevec/Project.toml
  lib/custatevec/src/cuStateVec.jl
  lib/custatevec/src/statevec.jl
  lib/utils/call.jl
Labels: enhancement, cuda libraries

#2288 Test suite changes
  test/Project.toml
  test/base/aqua.jl
  test/runtests.jl
Labels: tests

#2290 Fix mixed-buffer/mixed-shape broadcasts.
  src/broadcast.jl
  test/base/broadcast.jl
Labels: cuda array, bugfix

#2297 Make it possible to customize the CuIterator adaptor.
  src/iterator.jl
  test/base/iterator.jl
Labels: enhancement, cuda array

#2300 [CUSOLVER] Add tests for geqrf, orgqr and ormqr
  lib/cusolver/dense.jl
  test/libraries/cusolver/dense.jl
Labels: cuda libraries, tests

#2307 Fix RNG determinism when using wrapped arrays.
  src/random.jl
Labels: cuda array
