Repository JuliaGPU/CUDA.jl, pull requests merged in 2024-01, with the labels that each got.

#2213 CUSPARSE: Eagerly combine duplicate element on construction.
  lib/cusparse/conversions.jl
  test/libraries/cusparse.jl
Labels: enhancement, cuda array, cuda libraries

#2178 Update to CUTENSOR 2.0
  .buildkite/pipeline.yml
  lib/cutensor/Project.toml
  lib/cutensor/src/cuTENSOR.jl
  lib/cutensor/src/error.jl
  lib/cutensor/src/interfaces.jl
  lib/cutensor/src/libcutensor.jl
  lib/cutensor/src/operations.jl
  lib/cutensor/src/tensor.jl
  lib/cutensor/src/types.jl
  lib/cutensor/src/utils.jl
  lib/cutensor/src/wrappers.jl
  lib/cutensor/test/base.jl
  lib/cutensor/test/contractions.jl
  lib/cutensor/test/elementwise_binary.jl
  lib/cutensor/test/elementwise_trinary.jl
  lib/cutensor/test/permutations.jl
  lib/cutensor/test/reductions.jl
  lib/cutensor/test/runtests.jl
  res/wrap/Manifest.toml
  res/wrap/cutensor.toml
  res/wrap/libcutensor_epilogue.jl
Labels: enhancement

#2232 Add a note about threaded for-blocks.
  docs/src/usage/multitasking.md
Labels: documentation

#2234 cuTENSOR plan handling changes.
  lib/cutensor/src/interfaces.jl
  lib/cutensor/src/operations.jl
  lib/cutensor/src/types.jl
  lib/cutensor/test/contractions.jl
  lib/cutensor/test/elementwise_binary.jl
  lib/cutensor/test/elementwise_trinary.jl
  lib/cutensor/test/permutations.jl
  lib/cutensor/test/reductions.jl
Labels: cuda libraries

#1944 CuSparseArrayCSR (N dim array) with batched matmatmul (bmm)
  lib/cusparse/CUSPARSE.jl
  lib/cusparse/array.jl
  lib/cusparse/batched.jl
  lib/cusparse/device.jl
  lib/cusparse/generic.jl
  lib/cusparse/helpers.jl
  lib/cusparse/util.jl
  test/libraries/cusparse/bmm.jl
Labels: enhancement, cuda array

#2242 CUBLAS: Support more strided inputs
  lib/cublas/linalg.jl
  src/device/utils.jl
  test/base/aqua.jl
  test/libraries/cublas.jl
Labels: enhancement, cuda libraries

#2247 Make `@device_code_sass` work with non-Julia kernels.
  src/compiler/reflection.jl
  test/core/execution.jl
Labels: enhancement, cuda kernels

#2256 Reduce locking in the handle cache
  lib/utils/cache.jl
Labels: enhancement, performance
