Repository JuliaGPU/CUDA.jl, pull requests merged in 2025-04, with the labels that each got.

#2662 Support disabling implicit synchronization
  src/array.jl
  src/memory.jl
  test/base/array.jl
Labels: cuda array, performance

#2739 More tests for CuContext
  test/core/cudadrv.jl
Labels: tests

#2744 More tests and better error type for cusparse generic
  lib/cusparse/generic.jl
  test/libraries/cusparse/generic.jl
Labels: cuda libraries, tests

#2740 Fill in missing KA functionality (KA.functional + sparse matrices adaption from CUDAbackend)
  src/CUDAKernels.jl
  test/base/kernelabstractions.jl
Labels: enhancement

#2748 Simple tests for check and explain_eltype
  test/base/array.jl
Labels: tests

#2749 Test for printing OutOfGPUMemoryError
  test/core/pool.jl
Labels: tests

#2751 Test for parse_limit
  test/core/pool.jl
Labels: tests

#2756 Broaden check for eltypes to make sure we don't allow invalid stuff
  src/array.jl
  test/base/array.jl
Labels: cuda array, tests

#2758 More array tests
  test/base/array.jl
Labels: cuda array, tests

#2733 Very rough implementation of bcast for CuSparseVector
  lib/cusparse/broadcast.jl
  lib/cusparse/device.jl
  test/libraries/cusparse/broadcast.jl
Labels: enhancement, cuda array

#2759 A few more tests for CUSOLVER Q mats
  test/libraries/cusolver/dense.jl
Labels: cuda libraries, tests

#2760 More tests for CuArrayPtr
  test/base/texture.jl
Labels: cuda array, tests
